### ISSUE TITLE
Debezium version upgrade 2.0 Final

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#137]
Debezium version upgrade 2.0 Final

**Comment by subkanthi** [comment]
Debezium 2.x does not bundle confluent avroconverters.

org.apache.kafka.common.config.ConfigException: Invalid value io.confluent.connect.avro.AvroConverter for configuration key.converter: Class io.confluent.connect.avro.AvroConverter could not be found.
	at org.apache.kafka.common.config.ConfigDef.parseType(ConfigDef.java:744)
	at org.apache.kafka.common.config.ConfigDef.parseValue(ConfigDef.java:490)
	at org.apache.kafka.common.config.ConfigDef.parse(ConfigDef.java:483)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:113)
	at org.apache.kafka.common.config.AbstractConfig.<init>(AbstractConfig.java:133)
	at org.apache.kafka.connect.runtime.WorkerConfig.<init>(WorkerConfig.java:425)
	at org.apache.kafka.connect.runtime.distributed.DistributedConfig.<init>(DistributedConfig.java:550)
	at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:95)
	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:80)

**Comment by subkanthi** [comment]
Merged to develop.
