### ISSUE TITLE
Example with CollapsingMergeTree

### ISSUE THREAD

**Issue by geopet85** [Altinity/clickhouse-sink-connector#178]
Hi, thank you for the project. It seems really promising in the Kafka-Clickhouse space. 
I am trying a variation of the employees example, where the employees table in Clickhouse is already created and has CollapsingMergeTree engine, but I am getting errors in the sink side. 
I am also using the [2022-12-28](https://hub.docker.com/layers/altinity/clickhouse-sink-connector/2022-12-28/images/sha256-9aa8a0d985f4508885afdd57fcbdc5306a764a5c878e34bcba926e2c6257a4da?context=explore) tag of the docker image. 

I am creating the table with this command:

```
CREATE TABLE employees.employees
(
    `emp_no` Int32,
    `birth_date` Date32,
    `first_name` String,
    `last_name` String,
    `gender` String,
    `hire_date` Date32,
    `_sign` Int8,
    `_version` UInt64
)
ENGINE = CollapsingMergeTree(_sign)
PRIMARY KEY emp_no
ORDER BY emp_no
SETTINGS index_granularity = 8192;
```

and the errors I am seeing are like the following:

```
 2023-01-02 11:41:32,374 INFO   ||  *** QUERY***insert into employees(emp_no,birth_date,first_name,last_name,gender,hire_date,_sign,_version,_sign) select emp_no,birth_date,first_name,last_name,gender,hire_date,_sign,_version,_sign from input('emp_no Int32,birth_date Date32,first_name String,last_name String,gender String,hire_date Date32,_sign Int8,_version UInt64,_sign Int8')   [com.altinity.clickhouse.sink.connector.db.DbWriter]
sink              | 2023-01-02 11:41:32,382 INFO   ||  *** QUERY***insert into employees(emp_no,birth_date,first_name,last_name,gender,hire_date,_sign,_version,_sign) select emp_no,birth_date,first_name,last_name,gender,hire_date,_sign,_version,_sign from input('emp_no Int32,birth_date Date32,first_name String,last_name String,gender String,hire_date Date32,_sign Int8,_version UInt64,_sign Int8')   [com.altinity.clickhouse.sink.connector.db.DbWriter]
sink              | 2023-01-02 11:41:32,385 ERROR  ||  ******* ERROR inserting Batch *****************   [com.altinity.clickhouse.sink.connector.db.DbWriter]
sink              | java.sql.SQLException: Missing value for parameter #7 [_sign Int8]
sink              | 	at com.clickhouse.jdbc.SqlExceptionUtils.clientError(SqlExceptionUtils.java:73)
sink              | 	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:320)
sink              | 	at com.altinity.clickhouse.sink.connector.db.DbWriter.addToPreparedStatementBatch(DbWriter.java:458)
sink              | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.flushRecordsToClickHouse(ClickHouseBatchRunnable.java:228)
sink              | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:189)
sink              | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:105)
sink              | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
sink              | 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
sink              | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
sink              | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
sink              | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
sink              | 	at java.base/java.lang.Thread.run(Thread.java:829)
sink              | 2023-01-02 11:41:32,388 ERROR  ||  ******* ERROR inserting Batch *****************   [com.altinity.clickhouse.sink.connector.db.DbWriter]
sink              | java.sql.SQLException: Missing value for parameter #7 [_sign Int8]
sink              | 	at com.clickhouse.jdbc.SqlExceptionUtils.clientError(SqlExceptionUtils.java:73)
sink              | 	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:320)
sink              | 	at com.altinity.clickhouse.sink.connector.db.DbWriter.addToPreparedStatementBatch(DbWriter.java:458)
sink              | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.flushRecordsToClickHouse(ClickHouseBatchRunnable.java:228)
sink              | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:189)
sink              | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:105)
sink              | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
sink              | 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
sink              | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
sink              | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
sink              | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
sink              | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

It seems that 2 `_sign` columns are being added in the insert statement.
Could you let me know of potential configuration changes I need to do, as well as update the [mutable_data](https://github.com/Altinity/clickhouse-sink-connector/blob/develop/doc/mutable_data.md) page with a CollapsingMergeTree example? 

Thanks

**Comment by aadant** [comment]
I would recommend to use the ReplacingMergeTree engine instead. The sink connector is fully tested with this engine and I think we should explicitly de-support Collapsible engines. There are a lot of development in the ReplacingMergeTree space see for example https://altinity.com/blog/replacingmergetree-and-crazy-clickhouse-stuff-the-december-sf-bay-area-clickhouse-meetup

**Comment by geopet85** [comment]
Thanks @aadant. I wasn't aware of the new parameters to improve final performance so we will give them a go. We were hoping to deduplicate our tables deriving from postgres tables using the CollapsingMergeTree engine instead, and that's why I asked on their integration with the sink connector.

**Comment by aadant** [comment]
@geopet85 did you figure out ?  Can this be closed ?
