### ISSUE TITLE
Explain why run sink-connector-lightweight with mysql example table `employees_predated` with snapmode has some record

### ISSUE THREAD

**Issue by tuanuet** [Altinity/clickhouse-sink-connector#242]
Explain why run sink-connector-lightweight with mysql example table `employees_predated` with snapmode has some record

Just like if table doesn't have primary key, record will be remove??

**Comment by subkanthi** [comment]
@tuanuet , I noticed that the records are not replicated because of a bug with translating `enum` data types. Are u referring to the same issue?

```
debezium-embedded_1  | java.lang.NumberFormatException: For input string: "'M'"
debezium-embedded_1  | 	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
debezium-embedded_1  | 	at java.base/java.lang.Integer.parseInt(Integer.java:638)
debezium-embedded_1  | 	at java.base/java.lang.Integer.parseInt(Integer.java:770)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.ddl.parser.MySqlDDLParserListenerImpl.getClickHouseDataType(MySqlDDLParserListenerImpl.java:412)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.ddl.parser.MySqlDDLParserListenerImpl.parseCreateTable(MySqlDDLParserListenerImpl.java:341)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.ddl.parser.MySqlDDLParserListenerImpl.enterColumnCreateTable(MySqlDDLParserListenerImpl.java:287)
debezium-embedded_1  | 	at io.debezium.ddl.parser.mysql.generated.MySqlParser$ColumnCreateTableContext.enterRule(MySqlParser.java:5252)
debezium-embedded_1  | 	at org.antlr.v4.runtime.tree.ParseTreeWalker.enterRule(ParseTreeWalker.java:50)
debezium-embedded_1  | 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:33)
debezium-embedded_1  | 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
debezium-embedded_1  | 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
debezium-embedded_1  | 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
debezium-embedded_1  | 	at org.antlr.v4.runtime.tree.ParseTreeWalker.walk(ParseTreeWalker.java:36)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.ddl.parser.MySQLDDLParserService.parseSql(MySQLDDLParserService.java:65)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.performDDLOperation(DebeziumChangeEventCapture.java:82)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.processEveryChangeRecord(DebeziumChangeEventCapture.java:166)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.lambda$setupDebeziumEventCapture$1(DebeziumChangeEventCapture.java:283)
debezium-embedded_1  | 	at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$0(ConvertingEngineBuilder.java:90)
debezium-embedded_1  | 	at io.debezium.embedded.EmbeddedEngine$1.handleBatch(EmbeddedEngine.java:518)
debezium-embedded_1  | 	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:913)
debezium-embedded_1  | 	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:229)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.setupDebeziumEventCapture(DebeziumChangeEventCapture.java:310)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.setup(DebeziumChangeEventCapture.java:338)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.ClickHouseDebeziumEmbeddedApplication.start(ClickHouseDebeziumEmbeddedApplication.java:81)
debezium-embedded_1  | 	at com.altinity.clickhouse.debezium.embedded.ClickHouseDebeziumEmbeddedApplication.main(ClickHouseDebeziumEmbeddedApplication.java:65)

```

**Comment by subkanthi** [comment]
Enum data types are now supported and tested.
