### ISSUE TITLE
DATA TYPE MAPPING not found: TYPE:arraySCHEMA NAME:null

### ISSUE THREAD

**Issue by zhangtinglu** [Altinity/clickhouse-sink-connector#294]
PG Version:  14.0
CK Version:  22.9.7

test=# \d+ public.test                                               
-----------------------+--------------------------+----------+----------+-------------------------------------------+----------+----------+------
 id                    | bigint                   |          | not null | nextval('user_searcher_id_seq'::regclass) | plain    |          |
 c1_location           | geometry                 |          |          |                                           | main     |          |
 c2_location           | geometry                 |          |          |                                           | main     |          |
 c3_arrays             | integer[]                |          |          |                                           | extended |          |

postgresql table include  integer[]    type

137083 2023-08-22 07:48:33.298 [pool-1-thread-7] ERROR com.altinity.clickhouse.sink.connector.db.operations.ClickHouseTableOperationsBase  -  **** DATA TYPE MAPPING not found: TYPE:arraySCHEMA NAME:null
137083 2023-08-22 07:48:33.298 [pool-1-thread-7] INFO com.altinity.clickhouse.sink.connector.db.operations.ClickHouseAutoCreateTable  - **** AUTO CREATE TABLE CREATE TABLE user_searcher(`id` Int64 NOT NULL,`user_id` Int32 NOT NULL,`name` String NOT NULL,`real_name` String NULL,`gender` String NOT NULL,`weight` Float32 NOT NULL,`height` Int32 NOT NULL,`birthdate` Date32 NOT NULL,`own_car` String NULL,`own_house` String NULL,`house_addr` String NOT NULL,`income_range_min` Int32 NOT NULL,`income_range_max` Int32 NOT NULL,`industry` String NOT NULL,`position` String NOT NULL,`school` String NOT NULL,`education` Int32 NOT NULL,`residence` String NOT NULL,`hometown` String NOT NULL,`marital_status` String NULL,`search_min_age` Int32 NOT NULL,`search_max_age` Int32 NOT NULL,`search_min_height` Int32 NOT NULL,`search_max_height` Int32 NOT NULL,`search_min_weight` Int32 NOT NULL,`search_max_weight` Int32 NOT NULL,`search_min_income` Int32 NOT NULL,`search_max_income` Int32 NOT NULL,`search_min_edu` Int32 NOT NULL,`search_max_edu` Int32 NOT NULL,`search_house` String NOT NULL,`search_residence` String NOT NULL,`created_time` DateTime64(6) NOT NULL,`updated_time` DateTime64(6) NOT NULL,`active_time` DateTime64(6) NULL,`city_location` String NULL,`last_location` String NULL,`recommend_type` Int32 NULL,`identity_verify` Int32 NULL,`search_hometown` String NOT NULL,`search_marital_status` String NOT NULL,`search_car` String NOT NULL,`search_same_city` String NOT NULL,`exposure` Int16 NOT NULL,`tag_item_ids` null NULL,`_sign` Int8,`_version` UInt64) ENGINE = ReplacingMergeTree(_version) PRIMARY KEY(id) ORDER BY(id)
140988 2023-08-22 07:48:37.203 [debezium-postgresconnector-embeddedconnector-change-event-source-coordinator] INFO io.debezium.relational.RelationalSnapshotChangeEventSource  -     Exported 894264 records for table 'yay.user_searcher' after 00:02:18.935
140999 2023-08-22 07:48:37.214 [pool-1-thread-7] ERROR com.altinity.clickhouse.sink.connector.db.DbWriter  - **** Error creating table ***user_searcher
java.sql.SQLException: Code: 62. DB::Exception: Syntax error: failed at position 1366 ('NULL'): NULL,`_sign` Int8,`_version` UInt64) ENGINE = ReplacingMergeTree(_version) PRIMARY KEY(id) ORDER BY(id). Expected one of: DEFAULT, MATERIALIZED, ALIAS, EPHEMERAL, AUTO_INCREMENT. (SYNTAX_ERROR) (version 22.9.7.34 (official build))
, server ClickHouseNode [uri=http://10.10.1.202:8123/test, options={custom_settings=allow_experimental_object_type=1,client_name=Agent_1}]@-672965702
    at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
    at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
    at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
    at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:120)
    at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:474)
    at com.altinity.clickhouse.sink.connector.db.operations.ClickHouseTableOperationsBase.runQuery(ClickHouseTableOperationsBase.java:103)
    at com.altinity.clickhouse.sink.connector.db.operations.ClickHouseAutoCreateTable.createNewTable(ClickHouseAutoCreateTable.java:32)
    at com.altinity.clickhouse.sink.connector.db.DbWriter.<init>(DbWriter.java:120)
    at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.getDbWriterForTable(ClickHouseBatchRunnable.java:133)
    at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:148)
    at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:101)
    at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
    at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
    at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Code: 62. DB::Exception: Syntax error: failed at position 1366 ('NULL'): NULL,`_sign` Int8,`_version` UInt64) ENGINE = ReplacingMergeTree(_version) PRIMARY KEY(id) ORDER BY(id). Expected one of: DEFAULT, MATERIALIZED, ALIAS, EPHEMERAL, AUTO_INCREMENT. (SYNTAX_ERROR) (version 22.9.7.34 (official build))

**Comment by subkanthi** [comment]
@zhangtinglu thanks for creating the issue, working on mapping postgres array data types to ClickHouse Array data type.

**Comment by subkanthi** [comment]
Fixed, please try the `latest` tag.
