### ISSUE TITLE
java.util.ConcurrentModificationException from the DbWriter

### ISSUE THREAD

**Issue by aadant** [Altinity/clickhouse-sink-connector#319]
```
debezium-embedded_1  | 169278 2023-10-19 19:24:03.281 [pool-1-thread-2] ERROR com.altinity.clickhouse.sink.connector.db.DbWriter  - ******* ERROR inserting Batch *****************
debezium-embedded_1  | java.util.ConcurrentModificationException
debezium-embedded_1  | 	at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1043)
debezium-embedded_1  | 	at java.base/java.util.ArrayList$Itr.next(ArrayList.java:997)
debezium-embedded_1  | 	at com.altinity.clickhouse.sink.connector.db.DbWriter.addToPreparedStatementBatch(DbWriter.java:451)
debezium-embedded_1  | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.flushRecordsToClickHouse(ClickHouseBatchRunnable.java:198)
debezium-embedded_1  | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:169)
debezium-embedded_1  | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:101)
debezium-embedded_1  | 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
debezium-embedded_1  | 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
debezium-embedded_1  | 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
debezium-embedded_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
debezium-embedded_1  | 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
debezium-embedded_1  | 	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by aadant** [comment]
affects 2023-10-17 release

**Comment by jramorim13** [comment]
Hello.
I'm having the same problem. Have you had any feedback?

**Comment by jramorim13** [comment]
Hello @aadant. 
I,m with same problems in my infrastructure.  You have any news?

**Comment by aadant** [comment]
@subkanthi should release a stable release that fixes this issue. Do you know if there is a recent build that fixes the issue ?

**Comment by subkanthi** [comment]
@jramorim13 , we are working on an improved build process, we will have a new release in a couple of days.

**Comment by subkanthi** [comment]
Fixed in latest release, `ConcurrentLinkedQueue` `poll` is used instead of iterating through elements.
