### ISSUE TITLE
Python utility `clickhouse_table_checksum` fails for `data_types` database

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#358]
```
2023-11-03 13:58:30,788 - ERROR - MainThread - Traceback (most recent call last):
  File "/home/kanthi/.local/lib/python3.10/site-packages/clickhouse_driver/dbapi/cursor.py", line 111, in execute
    response = execute(
  File "/home/kanthi/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 296, in execute
    rv = self.process_ordinary_query(
  File "/home/kanthi/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 482, in process_ordinary_query
    return self.receive_result(with_column_types=with_column_types,
  File "/home/kanthi/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 143, in receive_result
    return result.get_result()
  File "/home/kanthi/.local/lib/python3.10/site-packages/clickhouse_driver/result.py", line 50, in get_result
    for packet in self.packet_generator:
  File "/home/kanthi/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 159, in packet_generator
    packet = self.receive_packet()
  File "/home/kanthi/.local/lib/python3.10/site-packages/clickhouse_driver/client.py", line 176, in receive_packet
    raise packet.exception
clickhouse_driver.errors.ServerException: Code: 47.
DB::Exception: Missing columns: '_sign' while processing query: 'SELECT concat(toString(my_row_id), if(col1 IS NULL, '', concat('#', toString(col1))), if(col2 IS NULL, '', concat('#', toString(col2))), if(col3 IS NULL, '', concat('#', toString(col3))), '#', toString(_version), '#', toString(is_deleted), '#', if(col1 IS NULL, '1', '0'), if(col2 IS NULL, '1', '0'), if(col3 IS NULL, '1', '0')) AS hash FROM test.add_test FINAL WHERE (1 = 1) AND (_sign > 0) ORDER BY my_row_id ASC', required columns: '_sign' 'my_row_id' 'col2' '_version' 'col1' 'col3' 'is_deleted', maybe you meant: 'my_row_id', 'col2', '_version', 'col1', 'col3' or 'is_deleted'. Stack trace:


```

```
python3 db_compare/mysql_table_checksum.py --mysql_host localhost --mysql_user root --mysql_password root  --mysql_database $DATABASE --tables_regex "^*" --debug_output
python3 db_compare/clickhouse_table_checksum.py --clickhouse_host localhost --clickhouse_user root --clickhouse_password root  --clickhouse_database test --tables_regex "^*" --debug_output --exclude_columns=_sign

````

**Comment by aadant** [comment]
it is fixed now
use 
```
 --sign_column ""
```

we could default it to empty string or do it automatically if the columns is in the list of excluded column

**Comment by subkanthi** [comment]
Added to python documentation.
