### ISSUE TITLE
java.lang.ClassCastException: class java.lang.Byte cannot be cast to class java.lang.Integer ERROR

### ISSUE THREAD

**Issue by jramorim13** [Altinity/clickhouse-sink-connector#385]
Hi guys.
We are experiencing the following error in the connector:

`ERROR  ||  ******* ERROR inserting Batch *****************   [com.altinity.clickhouse.sink.connector.db.DbWriter]
java.lang.ClassCastException: class java.lang.Byte cannot be cast to class java.lang.Integer (java.lang.Byte and java.lang.Integer are in module java.base of loader 'bootstrap')
        at com.altinity.clickhouse.sink.connector.converters.ClickHouseDataTypeMapper.convert(ClickHouseDataTypeMapper.java:175)
        at com.altinity.clickhouse.sink.connector.db.DbWriter.insertPreparedStatement(DbWriter.java:603)
        at com.altinity.clickhouse.sink.connector.db.DbWriter.addToPreparedStatementBatch(DbWriter.java:466)
        at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.flushRecordsToClickHouse(ClickHouseBatchRunnable.java:199)
        at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:169)
        at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:101)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)`

As a result, the connector is unable to convert data from some tables.
Is there a workaround for this error?

We are using the version clickhouse-kafka-sink-connector-0.0.4.jar

**Comment by subkanthi** [comment]
Hi @jramorim13 ,
can you please provide the schema of the MySQL tables that's getting this exception.

**Comment by aadant** [comment]
It would also help to have the ClickHouse table.

**Comment by jramorim13** [comment]
The connection is made via a debezuim connector that puts the data from the Oracle tables into Kafka. Then the Altinity connector reads the messages in Kafka and places them in Clickhouse. But when it comes to putting this data into Clickhouse, the connector is giving this error above when trying to convert the data.

So the table is empty in the clickhouse

**Comment by aadant** [comment]
@jramorim13 we only support MySQL / Postgres / MongoDB at the moment, not Oracle database yet. What error do you get in the log file ?
Feel free to contribute if you can fix the issue.
Pretty sure this is a data type mapping issue (a blob or binary field that is not recognized).
In CH it would be escaped at base64 or hex not to lose information.
Please paste the Oracle table that is failing.
