### ISSUE TITLE
Sink connector kafka - time out creating topic.

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#411]
023-12-06 22:50:19,175 INFO   ||  Creating topic 'SERVER5432.topic'   [org.apache.kafka.connect.runtime.AbstractWorkerSourceTask]
2023-12-06 22:51:13,656 WARN   ||  WorkerSourceTask{id=debezium-connector-ti_daily-0} Failed to send record to topic 'SERVER5432.topic' and partition 'null' due to an unrecoverable exception:    [org.apache.kafka.connect.runtime.AbstractWorkerSourceTask]
org.apache.kafka.connect.errors.ConnectException: Timed out while checking for or creating topic(s) 'SERVER5432.topic'. This could indicate a connectivity issue, unavailable topic partitions, or if this is your first use of the topic it may have taken too long to create.
        at org.apache.kafka.connect.util.TopicAdmin.createOrFindTopics(TopicAdmin.java:419)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.maybeCreateTopic(AbstractWorkerSourceTask.java:511)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.sendRecords(AbstractWorkerSourceTask.java:398)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:354)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:72)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.common.errors.TimeoutException: The request timed out.
2023-12-06 22:51:27,293 ERROR  ||  WorkerSourceTask{id=debezium-connector-ti_daily-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted   [org.apache.kafka.connect.runtime.WorkerTask]
org.apache.kafka.connect.errors.ConnectException: Timed out while checking for or creating topic(s) 'SERVER5432.topic'. This could indicate a connectivity issue, unavailable topic partitions, or if this is your first use of the topic it may have taken too long to create.
        at org.apache.kafka.connect.util.TopicAdmin.createOrFindTopics(TopicAdmin.java:419)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.maybeCreateTopic(AbstractWorkerSourceTask.java:511)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.sendRecords(AbstractWorkerSourceTask.java:398)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.execute(AbstractWorkerSourceTask.java:354)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:189)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:244)
        at org.apache.kafka.connect.runtime.AbstractWorkerSourceTask.run(AbstractWorkerSourceTask.java:72)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.common.errors.TimeoutException: The request timed out.

**Comment by subkanthi** [comment]
Debezium uses zookeeper client to create topics
```
   /**
     * Create the specified topic.
     *
     * @param topic the name of the topic to create
     * @param numPartitions the number of partitions for the topic
     * @param replicationFactor the replication factor for the topic
     */
    public void createTopic(String topic, int numPartitions, int replicationFactor) {
        RackAwareMode rackAwareMode = null;
        getAdminZkClient().createTopic(topic, numPartitions, replicationFactor, new Properties(), rackAwareMode, false);
```
