### ISSUE TITLE
Can't follow the quick start guide

### ISSUE THREAD

**Issue by erwannbst** [Altinity/clickhouse-sink-connector#526]
Hello, I tried to follow the quick start guide.

I installed docker on ubuntu.

Then

```
cd sink-connector-lightweight/docker
export CLICKHOUSE_SINK_CONNECTOR_LT_IMAGE=altinity/clickhouse-sink-connector:2.0.0-lt
docker compose -f docker-compose-postgres.yml up --renew-anon-volumes
```

But I get

```
WARN[0000] The "CLICKHOUSE_SINK_CONNECTOR_LT_IMAGE" variable is not set. Defaulting to a blank string.
service "clickhouse-sink-connector-lt" has neither an image nor a build context specified: invalid compose project
```

And the container doesnt starts

**Comment by subkanthi** [comment]
Are you on the `develop` branch, not able to reproduce it
```
(base) :~/Documents/GITHUB/clickhouse-sink-connector/sink-connector-lightweight/docker$ export CLICKHOUSE_SINK_CONNECTOR_LT_IMAGE=altinity/clickhouse-sink-connector:2.0.0-lt
(base) :~/Documents/GITHUB/clickhouse-sink-connector/sink-connector-lightweight/docker$ docker-compose -f docker-compose-postgres.yml up --renew-anon-volumes
Creating network "docker_default" with the default driver
Recreating docker_postgres_1                   ... done
Creating clickhouse          ... done
Creating prometheus          ... done
Creating docker_grafana_1                      ... done
Creating docker_clickhouse-sink-connector-lt_1 ... 
Creating docker_clickhouse-sink-connector-lt_1 ... done
Stopping docker_grafana_1                      ... 
Stopping docker_postgres_1                     ... 
Stopping prometheus                            ... 
Stopping clickhouse                            ... 
```

**Comment by erwannbst** [comment]
<img width="1121" alt="Screenshot 2024-04-05 at 20 39 34" src="https://github.com/Altinity/clickhouse-sink-connector/assets/16354899/9787a0ff-8150-4739-a35d-4b6d9dbbd9f9">

Different outputs depending on `docker compose` as in the documentation or `docker-compose` like your comment

**Comment by subkanthi** [comment]
Im able to reproduce, can you try without `sudo`

```
(base) :~/Documents/GITHUB/clickhouse-sink-connector/sink-connector-lightweight/docker$ sudo docker-compose -f docker-compose-postgres.yml up
WARNING: The CLICKHOUSE_SINK_CONNECTOR_LT_IMAGE variable is not set. Defaulting to a blank string.
Traceback (most recent call last):
  File "docker-compose", line 3, in <module>
  File "compose/cli/main.py", line 81, in main
  File "compose/cli/main.py", line 203, in perform_command
  File "compose/metrics/decorator.py", line 18, in wrapper
  File "compose/cli/main.py", line 1186, in up
  File "compose/cli/main.py", line 1182, in up
  File "compose/project.py", line 664, in up
  File "compose/service.py", line 352, in ensure_image_exists
  File "compose/service.py", line 378, in image
  File "docker/utils/decorators.py", line 17, in wrapped
docker.errors.NullResource: Resource ID was not provided
[476683] Failed to execute script docker-compose
(base) :~/Documents/GITHUB/clickhouse-sink-connector/sink-connector-lightweight/docker$ docker-compose -f docker-compose-postgres.yml up
Starting prometheus ... 
Starting clickhouse ... 

```

**Comment by erwannbst** [comment]
Thank you it works with `docker compose` after having followed [Managing Docker as a non-root user](https://docs.docker.com/engine/install/linux-postinstall/#manage-docker-as-a-non-root-user)
