### ISSUE TITLE
Sink Connector - ClickHouse Connection Issue

### ISSUE THREAD

**Issue by PraveenBalaji001** [Altinity/clickhouse-sink-connector#551]
Description - I am facing this issue while running the light weight sink connector in my system, whether clickhouse version needs to be updated?

clickhouse-server --version
ClickHouse server version 22.2.2.1.

Logs -

[Sink connector Debezium Event Thread] ERROR com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture - Retrying - try number:3
[Sink connector Debezium Event Thread] INFO com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture - CREATING DEBEZIUM STORAGE Database: create database if not exists altinity_sink_connector
[Sink connector Debezium Event Thread] ERROR com.altinity.clickhouse.sink.connector.db.BaseDbWriter - Error creating ClickHouse connectionjava.sql.SQLException: Connect to http://localhost:8123 [/localhost] failed: Connection refused, server ClickHouseNode [uri=http://localhost:8123/table, options={custom_settings=allow_experimental_object_type=1,insert_allow_materialized_columns=1,client_name=Client_1}]@295694949
[Sink connector Debezium Event Thread] ERROR com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture - Error creating Debezium storage database
java.lang.NullPointerException: Cannot invoke "com.clickhouse.jdbc.ClickHouseConnection.prepareStatement(String)" because "this.conn" is null
        at com.altinity.clickhouse.sink.connector.db.BaseDbWriter.executeQuery(BaseDbWriter.java:133)
        at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.createDatabaseForDebeziumStorage(DebeziumChangeEventCapture.java:315)
        at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.setupDebeziumEventCapture(DebeziumChangeEventCapture.java:489)
        at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture$3.handle(DebeziumChangeEventCapture.java:535)
        at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:500)
        at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:229)
        at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.lambda$setupDebeziumEventCapture$3(DebeziumChangeEventCapture.java:564)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by subkanthi** [comment]
Hi @PraveenBalaji001 , as shown in the logs, sink connector is unable to connect to ClickHouse. 
```
ClickHouse connectionjava.sql.SQLException: Connect to http://localhost:8123/ [/localhost] failed: Connection refused, server ClickHouseNode [uri=http://localhost:8123/table, options=
```
