### ISSUE TITLE
Improve bulk operations performance

### ISSUE THREAD

**Issue by ZlobnyiSerg** [Altinity/clickhouse-sink-connector#574]
I've tested initial load on large datasets and got around 500 rows per second on powerful PC. This is very slow performance compared to built-in ClickHouse Bulk operations with binary transfer support.
Can you consider using official ClickHouse connector as part for data transfer? https://github.com/ClickHouse/clickhouse-kafka-connect/blob/main/src/main/java/com/clickhouse/kafka/connect/sink/db/ClickHouseWriter.java
It would be good to focus from your side on target database structure and reuse official implementation for data transfer itself.

**Comment by subkanthi** [comment]
Thanks @ZlobnyiSerg , will take a look, did you find  the throughput was better  with the official clickhouse connector ( Binary transfer), was the setup still using debezium source connector?

**Comment by aadant** [comment]
@ZlobnyiSerg if the source is MySQL you can do the initial bulk load as consistent snapshot.
See the python directory for utilities.
I transferred 28TB in a couple of hours, with a CH database of 3TB. mysql_dumper.py uses mysqlsh under the hood.

**Comment by aadant** [comment]
@subkanthi there are parameters to tune to insert throughput (https://github.com/Altinity/clickhouse-sink-connector/issues/576)

**Comment by ZlobnyiSerg** [comment]
> @ZlobnyiSerg if the source is MySQL you can do the initial bulk load as consistent snapshot. See the python directory for utilities. I transferred 28TB in a couple of hours, with a CH database of 3TB. mysql_dumper.py uses mysqlsh under the hood.

No, our source is Postgres and solution to manually copy initial snapshots is not suitable for us - we have lot of tables and lot of warehouses "on-premise".

I didn't tested clickhouse connector, but I've tested bulk operations with own C# "data-pumper" - bulk performance was very fast with Clickhouse, unfortunatelly I don't recorded any digits. 

I will try to experiment with official connector later.

**Comment by aadant** [comment]
Insert performance is pretty good, I got several MB/s with
```
# Max number of records for the flush buffer.
buffer.max.records: "1000000"
# Maximum number of threads in the thread pool for processing CDC records.
thread.pool.size: 10
max.batch.size: 20000
max.queue.size: 100000
```

**Comment by cb-shreyassreenivas** [comment]
@ZlobnyiSerg are you referring to this script
https://github.com/Altinity/clickhouse-sink-connector/blob/develop/sink-connector/python/db_load/clickhouse_loader.py

Also, if we use that how do we start the CDC? How to set the binlog states for the connector?
TIA

**Comment by subkanthi** [comment]
> @ZlobnyiSerg are you referring to this script https://github.com/Altinity/clickhouse-sink-connector/blob/develop/sink-connector/python/db_load/clickhouse_loader.py
> 
> Also, if we use that how do we start the CDC? How to set the binlog states for the connector? TIA

@inai-shreyas , you can use the sink-connector-client program to set the CDC start position.

https://github.com/Altinity/clickhouse-sink-connector/blob/develop/doc/replication_start_position.md

**Comment by cb-shreyassreenivas** [comment]
@subkanthi Got it. But my concern is how can I find the position when I'm loading it. will the loader give the positions when it exits?

**Comment by subkanthi** [comment]
The current approach uses the batch insert using `input` function, which JDBC translates to a `RowBinary` batch format
https://github.com/ClickHouse/clickhouse-java/issues/1392

```
Hi @kvbfullstack, using input function in batch insert is something like the following. Behind the scene, there are chunked requests being sent to ClickHouse server for insertion.

insert into mytable format RowBinary
<serialized data in RowBinary format>
RE: batch size, it depends on partions, columns, and the volume. You may increase the batch size by multiply 10 and watch if server is comfortable to handle that.
```

**Comment by Jimerson21** [comment]
Hello everyone, 

I am having the same problem when trying to synchronize Clickhouse from an Aurora Serverless Mysql database.

The database has approximately 20 million records. But after a while of synchronizing I get the following exceptions

```
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "server-timer"
[pool-8-thread-1] INFO io.debezium.relational.RelationalSnapshotChangeEventSource -      Exported 1003258 of 7156113 records for table 'funnel_events' after 00:10:05.702

Exception in thread "HTTP-Dispatcher" [Sink connector Debezium Event Thread] INFO io.debezium.embedded.EmbeddedEngine - Stopping the task and engine
[Sink connector Debezium Event Thread] INFO io.debezium.connector.common.BaseSourceTask - Stopping down connector
java.lang.OutOfMemoryError: Java heap space
[Sink connector Debezium Event Thread] WARN io.debezium.pipeline.ChangeEventSourceCoordinator - Coordinator didn't stop in the expected time, shutting down executor now
[debezium-mysqlconnector-embeddedconnector-change-event-source-coordinator] ERROR io.debezium.relational.RelationalSnapshotChangeEventSource - Error during snapshot
java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:1638)
        at java.base/java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:435)
        at java.base/java.util.concurrent.ExecutorCompletionService.take(ExecutorCompletionService.java:200)
        at io.debezium.relational.RelationalSnapshotChangeEventSource.createDataEvents(RelationalSnapshotChangeEventSource.java:467)
        at io.debezium.relational.RelationalSnapshotChangeEventSource.doExecute(RelationalSnapshotChangeEventSource.java:165)
        at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:92)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:253)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:237)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:189)
        at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:137)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)
```
**This is my sink-connector-lightweight configuration, I am using the version: altinity/clickhouse-sink-connector:2.0.2-lt**

```
snapshot.mode: "initial"
snapshot.locking.mode: "none"
offset.flush.interval.ms: 5000
enable.snapshot.ddl: "true"
persist.raw.bytes: "false"
auto.create.tables: "true"
database.connectionTimeZone: "UTC"
clickhouse.datetime.timezone: "UTC"
restart.event.loop: "true"
restart.event.loop.timeout.period.secs: "3000"
buffer.flush.time.ms: "1000"
buffer.max.records: "50000"
thread.pool.size: 50
sink.connector.max.queue.size: "10000"
max.batch.size: 2048
max.queue.size: 6000
max.queue.size.in.bytes: 10000000
schema.history.internal.store.only.captured.tables.ddl: "true"
schema.history.internal.store.only.captured.databases.ddl: "true"
```

Thank you.

**Comment by subkanthi** [comment]
Hi @Jimerson21 , `2.0.2-lt` is old, can you please try `altinity/clickhouse-sink-connector:2.3.1-lt`, also you can try single threaded mode by adding
`single.threaded: "true"` to `config.yml`.

**Comment by Jimerson21** [comment]
> Hi @Jimerson21 , `2.0.2-lt` is old, can you please try `altinity/clickhouse-sink-connector:2.3.1-lt`, also you can try single threaded mode by adding `single.threaded: "true"` to `config.yml`.

Thanks for responding @subkanthi,

I understand, I will update it. Do you think the rest of the settings are ok?

I've been trying for hours to do the snapshot but after several minutes or hours the process stops. My Mysql database is not big.

**Comment by aadant** [comment]
@Jimerson21 I would recommend to take a snapshot using mysqlshell. we have toolings to do that.
Then replication from the snapshot position. It is much more efficient to dump and load compared to using a snapshot.
I did this with 10s of TB of MySQL data in the dump and load. The load time in CH is ridiculously fast :

see https://github.com/Altinity/clickhouse-sink-connector/issues/307#issuecomment-1896642623
