### ISSUE TITLE
_version and is_deleted fields cause null error  in Postgres to ClickHouse

### ISSUE THREAD

**Issue by glistman** [Altinity/clickhouse-sink-connector#608]
Hello,

I attempted to use the connector with the default configuration provided in the config_postgres.yml file. After replacing the default settings with my Postgres and Clickhouse database details in the cloud, I encountered the following error when I started the replicator:

`java.lang.RuntimeException: java.sql.SQLException: Cannot set null to non-nullable column #3 [_version UInt64]`

After addressing the issue with the _version field, I encountered another error:

`java.lang.RuntimeException: java.sql.SQLException: Cannot set null to non-nullable column #4 [is_deleted UInt8]`

I resolved this by modifying the PreparedStatementExecutor file at line 242 as follows:
![image](https://github.com/Altinity/clickhouse-sink-connector/assets/30837065/2d48dd7e-af79-4a35-8bdd-fb1f6f89e025)

`  } catch (DataException e) {
                // Struct .get throws a DataException
                // if the field is not present.
                // If the record was not supplied, we need to set it as null.
                if (colName.equals(IS_DELETED_COLUMN)) {
                    short isDeleted = (short) (ClickHouseConverter.CDC_OPERATION.DELETE.equals(record.getCdcOperation()) ? 1: 0);
                    ps.setShort(index, isDeleted);
                } else if (colName.equals(VERSION_COLUMN)) {
                    ps.setLong(index, System.nanoTime());
                } else {
                    ps.setNull(index, Types.OTHER);
                }
                continue;
            }`

This solution worked in my case, but I am not sure if it is the correct approach for the project.

Thank you for your assistance.

**Comment by subkanthi** [comment]
Hi @glistman , it will be good to understand the exception , this usually happens when the clickhouse columns
dont match the MySQL columns, will add a fix to print a better message.

can you please share the stack trace here, you can add a print/log to print the exception stack trace.
```
                ps.setNull(index, Types.OTHER);
                log.info("Exception", e);
                continue;
```

**Comment by glistman** [comment]
Hi,

The _versions and is_deleted fields come in the metadata but do not have a value.



```java
2024-05-24 16:27:16.883 ERROR - ******* ERROR inserting Batch *****************
java.sql.SQLException: Cannot set null to non-nullable column #14 [_version UInt64]
	at com.clickhouse.jdbc.SqlExceptionUtils.clientError(SqlExceptionUtils.java:73) ~[clickhouse-jdbc-0.6.0-shaded.jar:clickhouse-jdbc 0.6.0 (revision: cb8e198)]
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:341) ~[clickhouse-jdbc-0.6.0-shaded.jar:clickhouse-jdbc 0.6.0 (revision: cb8e198)]
	at com.altinity.clickhouse.sink.connector.db.batch.PreparedStatementExecutor.lambda$executePreparedStatement$0(PreparedStatementExecutor.java:158) ~[classes/:?]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) [?:?]
	at com.altinity.clickhouse.sink.connector.db.batch.PreparedStatementExecutor.executePreparedStatement(PreparedStatementExecutor.java:119) [classes/:?]
	at com.altinity.clickhouse.sink.connector.db.batch.PreparedStatementExecutor.addToPreparedStatementBatch(PreparedStatementExecutor.java:90) [classes/:?]
	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.flushRecordsToClickHouse(ClickHouseBatchRunnable.java:345) [classes/:?]
	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:311) [classes/:?]
	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:172) [classes/:?]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305) [?:?]
```

![image](https://github.com/Altinity/clickhouse-sink-connector/assets/30837065/b52e0956-bc4e-4fce-937c-2c51e839b0e1)

**Comment by captainpro-eng** [comment]
@subkanthi  any update on this?

**Comment by captainpro-eng** [comment]
@subkanthi this is issue getting if we create distribution engine table.

**Comment by subkanthi** [comment]
> [@subkanthi](https://github.com/subkanthi) this is issue getting if we create distribution engine table.

Hi @captainpro-eng , can u please share the postgres table schema and the config.yml (changes you made), so we can reproduce the error.

**Comment by captainpro-eng** [comment]
Hi @subkanthi Thanks for Reply. I tested this on mysql. Please find below schema of mysql table :- 

```CREATE TABLE progate_cdr_tbl_shard on cluster default
(
    call_id Int64,
    extra_attributes String,
    batch_id Int64,
    campaign_id Int64,
    lang_id Nullable(FixedString(4)),
    recipient Nullable(String),
    route_id Int32,
    cli Nullable(String),
    source_id Nullable(String),
    user_code Nullable(Int32),
    connection_type Nullable(String),
    email Nullable(String),
    operator LowCardinality(String),
    country LowCardinality(String),
    ivr_flow Nullable(String),
    custom_flow_name Nullable(String),
    processed_date Nullable(DateTime64),
    description Nullable(String),
    code Nullable(String),
    submission_date DateTime,
    submit_state String,
    voice_file_names Nullable(String),
    call_dial_time Nullable(DateTime64),
    call_answered_time Nullable(DateTime64),
    call_end_time Nullable(DateTime64),
    call_state Nullable(String),
    call_release_code Nullable(String),
    max_duration Nullable(Int32),
    call_duration Nullable(Int32),
    max_pulses Nullable(Int32),
    max_pulses_level1 Nullable(Int32),
    call_pulses Nullable(Int32),
    call_pulses_level1 Nullable(Int32),
    call_cost Nullable(Int32),
    call_cost_level1 Nullable(Int32),
    deduction_price Nullable(Int32),
    deduction_price_level1 Nullable(Int32),
    dtmf_inputs Nullable(String),
    dtmf_press_time Nullable(DateTime64),
    record_file_name Nullable(String),
    follow_on_sms_time Nullable(DateTime64),
    follow_on_sms_type Nullable(FixedString(20)),
    mdr_mid Nullable(Int64),
    retry_counter Nullable(Int32),
    retry_attempt Nullable(Int32),
    extra1 Nullable(String),
    extra2 Nullable(String),
    extra3 Nullable(String),
    operator_campaign_id Nullable(String),
    pulse_duration Nullable(Int32),
    pulse_duration_level1 Nullable(Int32),
    custom_sms_response Nullable(String),
    lead_url_response Nullable(String),
    sms_details Nullable(String),
    agent_call_state Nullable(String),
    agent_call_answered_time Nullable(DateTime64),
    agent_call_end_time Nullable(DateTime64),
    agent_call_release_code Nullable(String),
    agent_call_duration Nullable(Int32),
    patch_retry_attempted Nullable(Int32),
    agent_call_dial_time Nullable(DateTime64),
    agent_number Nullable(String),
    agent_converstion_duration Nullable(Int32),
    sip_code Nullable(String),
    agent_sip_code Nullable(String),
    all_dtmf_inputs Nullable(String),
    ring_duration1 Nullable(Int32),
    ring_duration2 Nullable(Int32),
    tts_counts Nullable(Int32),
    user_tts_rate Nullable(Int32),
    user_tts_amount Nullable(Int32),
    level1_tts_rate Nullable(Int32),
    level1_tts_amount Nullable(Int32),
    tts_content Nullable(String),
    charging_mode Nullable(String), `_version` UInt64, `is_deleted` UInt8
)
ENGINE = ReplacingMergeTree(_version,is_deleted)
PARTITION BY toYYYYMMDD(submission_date)
ORDER BY (call_id,route_id, submission_date)
PRIMARY KEY (call_id,route_id,submission_date)
SETTINGS index_granularity = 8192,
min_age_to_force_merge_seconds = 10,
min_age_to_force_merge_on_partition_only = true;

CREATE TABLE IF NOT EXISTS progate.progate_cdr_tbl ON CLUSTER default
AS progate.progate_cdr_tbl_shard
ENGINE = Distributed(default, progate, progate_cdr_tbl_shard, call_id);
```
sink connector inserting data on progate.progate_cdr_tbl table

**Comment by minguyen9988** [comment]
Verified fixed at develop head `d41888aa`.

The fix landed at the exact location you patched. `_version`, `_sign` and the RMT delete column are now excluded from the `setNull` fallback and bound by dedicated handlers instead:

`sink-connector/src/main/java/com/altinity/clickhouse/sink/connector/db/batch/PreparedStatementFieldMapper.java:241-257`
```java
} catch (DataException e) {
    // Struct .get throws a DataException if the field is not present.
    if (colName.equalsIgnoreCase(versionColumn) || colName.equalsIgnoreCase(signColumn) ||
            colName.equalsIgnoreCase(replacingMergeTreeDeleteColumn)) {
        // Ignore version and sign columns
    } else { ... }
```
They are then populated by `handleVersionColumn` (`:486-506`) and `handleReplacingMergeTreeDeleteColumn` (`:512+`), so the `Cannot set null to non-nullable column #3 [_version UInt64]` error no longer occurs.

On PostgreSQL specifically, `_version` is sourced from the LSN branch of `calculateVersion` (`ClickHouseStruct.java:832-833`). Note your suggested `System.nanoTime()` fallback was deliberately not adopted — LSN is monotonic and correct for RMT ordering, whereas `nanoTime` is not comparable across restarts.

Closing as fixed.
