### ISSUE TITLE
Error creating Debezium storage database message

### ISSUE THREAD

**Issue by Selfeer** [Altinity/clickhouse-sink-connector#636]
When trying to perform basic MySQL replication when using build from: https://github.com/Altinity/clickhouse-sink-connector/pull/614 we get the following error messages in sink connector

```
2024-06-10 22:23:46.207 ERROR - Error starting connectorjava.lang.IllegalStateException: Failed to create JDBC offset table: jdbc:clickhouse://clickhouse:8123/altinity_sink_connector Message:Unable to configure and start the 'io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore' offset backing store
2024-06-10 22:23:46.207 ERROR - Retrying - try number:0
2024-06-10 22:23:56.219 INFO  - CREATING DEBEZIUM STORAGE Database: create database if not exists altinity_sink_connector
2024-06-10 22:23:56.221 ERROR - Error creating Debezium storage database
java.sql.BatchUpdateException: Code: 81. DB::Exception: Database `null` doesn't exist. (UNKNOWN_DATABASE) (version 23.3.18.15 (official build))
    , server ClickHouseNode [uri=http://clickhouse:8123/null, options={custom_settings=allow_experimental_object_type=1,insert_allow_materialized_columns=1,client_name=Client_1}]@-1313045159
	at com.clickhouse.jdbc.SqlExceptionUtils.batchUpdateError(SqlExceptionUtils.java:107) ~[app.jar:?]
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeAny(SqlBasedPreparedStatement.java:219) ~[app.jar:?]
	at com.clickhouse.jdbc.internal.SqlBasedPreparedStatement.executeQuery(SqlBasedPreparedStatement.java:246) ~[app.jar:?]
	at com.altinity.clickhouse.sink.connector.db.BaseDbWriter.executeQuery(BaseDbWriter.java:133) ~[app.jar:?]
	at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.createDatabaseForDebeziumStorage(DebeziumChangeEventCapture.java:341) ~[app.jar:?]
	at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.setupDebeziumEventCapture(DebeziumChangeEventCapture.java:538) ~[app.jar:?]
	at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture$3.handle(DebeziumChangeEventCapture.java:587) ~[app.jar:?]
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:500) ~[app.jar:?]
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:229) ~[app.jar:?]
	at com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.lambda$setupDebeziumEventCapture$3(DebeziumChangeEventCapture.java:616) ~[app.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Configuration used:**

```yml
name: my_connector
database.hostname: mysql-master
database.port: '3306'
database.user: root
database.password: root
database.server.name: ER54
database.include.list: test
clickhouse.server.url: clickhouse
clickhouse.server.user: root
clickhouse.server.password: root
clickhouse.server.port: '8123'
database.allowPublicKeyRetrieval: 'true'
snapshot.mode: initial
offset.flush.interval.ms: '5000'
snapshot.locking.mode: none
connector.class: io.debezium.connector.mysql.MySqlConnector
offset.storage: io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore
offset.storage.jdbc.offset.table.name: altinity_sink_connector.replica_source_info
offset.storage.jdbc.url: jdbc:clickhouse://clickhouse:8123/altinity_sink_connector
offset.storage.jdbc.user: root
offset.storage.jdbc.password: root
offset.storage.jdbc.offset.table.ddl: |-
  CREATE TABLE if not exists %s
  (
      `id` String,
      `offset_key` String,
      `offset_val` String,
      `record_insert_ts` DateTime,
      `record_insert_seq` UInt64,
      `_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
  )
  ENGINE = ReplacingMergeTree(_version)
  ORDER BY id
  SETTINGS index_granularity = 8198
offset.storage.jdbc.offset.table.delete: delete from %s where 1=1
schema.history.internal: io.debezium.storage.jdbc.history.JdbcSchemaHistory
schema.history.internal.jdbc.url: jdbc:clickhouse://clickhouse:8123/altinity_sink_connector
schema.history.internal.jdbc.user: root
schema.history.internal.jdbc.password: root
schema.history.internal.jdbc.schema.history.table.ddl: |-
  CREATE TABLE if not exists %s
  (`id` VARCHAR(36) NOT NULL, `history_data` VARCHAR(65000), `history_data_seq` INTEGER, `record_insert_ts` TIMESTAMP NOT NULL, `record_insert_seq` INTEGER NOT NULL) ENGINE=ReplacingMergeTree(record_insert_seq) order by id
schema.history.internal.jdbc.schema.history.table.name: altinity_sink_connector.replicate_schema_history
replacingmergetree.delete.column: _sign
enable.snapshot.ddl: 'true'
database.connectionTimeZone: UTC
database.serverTimezone: UTC
clickhouse.datetime.timezone: UTC
auto.create.tables: 'true'
```

**Comment by subkanthi** [comment]
Fixed in #614 https://github.com/Altinity/clickhouse-sink-connector/pull/614
