### ISSUE TITLE
Debezium error with OffsetStorageWriter during snapshot process.

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#731]
```Error starting connector org.apache.kafka.connect.errors.ConnectException: OffsetStorageWriter is already flushing Message```

```Invalid call to OffsetStorageWriter beginFlush() while already flushing, the framework should not allow this```

**Comment by subkanthi** [comment]
# `OffsetStorageWriter is already flushing` in ClickHouseBatchRunnable

## Summary

Under load (and especially with `THREAD_POOL_SIZE > 1`), the lightweight sink connector
intermittently logs the following as an `ERROR` and aborts the current batch run:

```
[Sink Connector thread-pool-7] ERROR c.a.c.sink.connector.executor.ClickHouseBatchRunnable
  - ClickHouseBatchRunnable exception - Task(0)
org.apache.kafka.connect.errors.ConnectException: OffsetStorageWriter is already flushing
    at org.apache.kafka.connect.storage.OffsetStorageWriter.beginFlush(OffsetStorageWriter.java:120)
    at io.debezium.embedded.EmbeddedEngine.commitOffsets(EmbeddedEngine.java:905)
    at io.debezium.embedded.EmbeddedEngine.maybeFlush(EmbeddedEngine.java:891)
    at io.debezium.embedded.EmbeddedEngine$4.markBatchFinished(EmbeddedEngine.java:830)
    at io.debezium.embedded.ConvertingEngineBuilder$ConvertingChangeConsumer$1.markBatchFinished(ConvertingEngineBuilder.java:87)
    at c.a.c.sink.connector.executor.DebeziumOffsetManagement.acknowledgeRecords(DebeziumOffsetManagement.java:205)
    at c.a.c.sink.connector.executor.DebeziumOffsetManagement.checkIfBatchCanBeCommitted(DebeziumOffsetManagement.java:162)
    at c.a.c.sink.connector.executor.ClickHouseBatchRunnable.processBatch(ClickHouseBatchRunnable.java:453)
    at c.a.c.sink.connector.executor.ClickHouseBatchRunnable.runLegacyMode(ClickHouseBatchRunnable.java:382)
    at c.a.c.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:306)
    ...
```

## What the error means

Kafka Connect's `OffsetStorageWriter` allows only **one in-flight offset flush at a time**.
`beginFlush()` throws `ConnectException("OffsetStorageWriter is already flushing")` when it is
called while a previous flush has not completed:

```java
public synchronized boolean beginFlush() {
    if (flushing()) {   // toFlush != null -> a prior flush is still in progress
        throw new ConnectException("OffsetStorageWriter is already flushing");
    }
    ...
}
```

So the message means: **two offset flushes overlapped on the same, non-thread-safe
`OffsetStorageWriter`.**

## Root cause

Debezium's `EmbeddedEngine`, its `RecordCommitter`, and the underlying `OffsetStorageWriter`
are designed to be driven from the **single embedded-engine thread**. This connector instead
commits offsets from a **different set of threads**, and does so eagerly on every batch:

1. The engine runs on one dedicated thread and `handleBatch` only parses records and enqueues
   them; it does not commit offsets there.

   - `sink-connector-lightweight/.../cdc/DebeziumChangeEventCapture.java`
     - Engine runs on `singleThreadDebeziumEventExecutor` (a single-thread pool), `engine.run()`.
     - `handleBatch(...)` -> `appendToRecords(batch, config)` pushes to the `records` queue.

2. The engine is built with `OffsetCommitPolicy.always()`, so **every** `markBatchFinished()`
   performs a full `beginFlush()` + `doFlush()`:

   ```java
   .using(OffsetCommitPolicy.always())
   ```

3. Offsets are actually committed later, from the **worker thread pool**
   (`Sink Connector thread-pool-N`), when a batch is drained:

   - `ClickHouseBatchRunnable.processBatch()` ->
     `DebeziumOffsetManagement.checkIfBatchCanBeCommitted()` ->
     `acknowledgeRecords()` -> `record.getCommitter().markBatchFinished()`.

   ```java
   // DebeziumOffsetManagement.acknowledgeRecords(...)
   if (record.isLastRecordInBatch()) {
       record.getCommitter().markBatchFinished();   // -> EmbeddedEngine.commitOffsets -> beginFlush
   }
   ```

`checkIfBatchCanBeCommitted` and `acknowledgeRecords` are `static synchronized`, so they are
serialized *within this class*. But that lock does **not** coordinate with the embedded engine's
own commit/flush path (a different thread and a different lock). When a worker thread calls
`markBatchFinished()` while the engine's previous flush (or another overlapping commit) has not
completed yet, `beginFlush()` sees `flushing() == true` and throws.

The likelihood increases with:
- `THREAD_POOL_SIZE > 1` (multiple `ClickHouseBatchRunnable` workers polling the shared queue),
- `OffsetCommitPolicy.always()` (a flush on every batch),
- a slow/blocked offset backing store (the async `doFlush` future has not completed before the
  next `beginFlush`).

### Flow

```mermaid
flowchart TD
    engineThread["Debezium engine thread (single)"] -->|handleBatch parses + enqueues| queue["records queue"]
    queue --> w1["worker thread-pool-1"]
    queue --> w2["worker thread-pool-N"]
    w1 -->|markBatchFinished| commitA["EmbeddedEngine.commitOffsets -> beginFlush"]
    w2 -->|markBatchFinished| commitB["EmbeddedEngine.commitOffsets -> beginFlush"]
    engineThread -.->|its own maybeFlush| commitC["EmbeddedEngine.commitOffsets -> beginFlush"]
    commitA --> writer["OffsetStorageWriter (single, non-thread-safe)"]
    commitB --> writer
    commitC --> writer
    writer -->|second overlapping beginFlush| err["ConnectException: already flushing"]
```

## Impact

- Usually **transient and non-fatal**. The failure happens *after* the records were written to
  ClickHouse (in `processRecordsByTopic`), so no data is lost on this path — only the **offset
  commit for that batch is skipped this round**.
- `ClickHouseErrorClassifier` classifies it as retriable, so `currentBatch` is retained and
  retried on the next scheduled run (`ClickHouseBatchRunnable.run()` -> `catch` -> "Retriable ...").
- Practical downsides:
  - Log noise (logged at `ERROR` with a full stack trace).
  - The whole `processBatch` loop for that run is aborted at the commit step, so offset
    advancement can lag under sustained load if the collision happens repeatedly.

## Proposed fixes (options)

- **Option A - Serialize all offset commits with the engine (correct fix).** Ensure offset
  commit/flush only ever happens on one thread, or is guarded by the same lock the engine uses.
  Practically: route `markBatchFinished()`/offset commits through the single engine thread, or
  wrap commit in a single shared lock and retry `beginFlush` collisions.

- **Option B - Treat "already flushing" as benign (low-risk mitigation).** Catch the specific
  `ConnectException` with message `OffsetStorageWriter is already flushing` in
  `DebeziumOffsetManagement.acknowledgeRecords` / `ClickHouseBatchRunnable`, log it at
  `DEBUG`/`WARN`, and let the offset be committed on a subsequent flush instead of aborting the
  batch run as an `ERROR`.

- **Option C - Reduce flush contention.** Consider a less aggressive `OffsetCommitPolicy`
  (interval/periodic instead of `always()`), and/or commit once per drained queue rather than on
  every sub-batch, to shrink the window for overlapping flushes.

Recommended: **B now** (stop the error-level noise / batch aborts), then **A** as the durable fix.

## Affected code

- `sink-connector-lightweight/src/main/java/com/altinity/clickhouse/debezium/embedded/cdc/DebeziumChangeEventCapture.java`
  - Single engine thread + `OffsetCommitPolicy.always()` + enqueue-only `handleBatch`.
- `sink-connector/src/main/java/com/altinity/clickhouse/sink/connector/executor/DebeziumOffsetManagement.java`
  - `checkIfBatchCanBeCommitted()` (line ~151), `acknowledgeRecords()` (line ~191/205,
    `markBatchFinished()`).
- `sink-connector/src/main/java/com/altinity/clickhouse/sink/connector/executor/ClickHouseBatchRunnable.java`
  - `run()` (line ~306), `runLegacyMode()` (line ~382), `processBatch()` (line ~453/474),
    retriable-vs-fatal classification in the `catch` block (lines ~311-336).

## Environment / how to reproduce

- Component: `sink-connector-lightweight` (Debezium embedded engine).
- Trigger: sustained CDC load with `THREAD_POOL_SIZE > 1`, or a slow offset backing store.
- Frequency: intermittent; increases with throughput and worker-thread count.

Please attach: connector version, `THREAD_POOL_SIZE`, `buffer.flush.time.ms`,
`buffer.count`/`max.queue.size`, source DB type, and whether it self-recovers after the error.
