### ISSUE TITLE
Postgresql truncate breaks Lightweight Sink Connector

### ISSUE THREAD

**Issue by Roman2dot0** [Altinity/clickhouse-sink-connector#733]
I have config for lt (lightweight-sink-connector 2.2.1) without kafka with option 
**disable.drop.truncate: "false"**
for truncate replication, but it doesn't work.
So I decided to add [(debezium doc)](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-skipped-operations)
**skipped.operations: "none"**
and when I truncated table in PG got error with infinity loop of inserts after that

```
2024-08-01 20:50:36.077 INFO  - ****** Thread: Sink Connector thread-pool-8 Batch Size: 1 ******
2024-08-01 20:50:36.078 ERROR - ClickHouseBatchRunnable exception - Task(0)
java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because the return value of "com.altinity.clickhouse.sink.connector.model.ClickHouseStruct.getKafkaPartition()" is null
        at com.altinity.clickhouse.sink.connector.db.batch.GroupInsertQueryWithBatchRecords.groupQueryWithRecords(GroupInsertQueryWithBatchRecords.java:50) ~[app.jar:?]
        at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:326) ~[app.jar:?]
        at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:188) [app.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Roman2dot0** [comment]
CH 24.3
PG 16.3

**Comment by subkanthi** [comment]
Hi @Roman2dot0 , this configuration variable `disable.drop.truncate: "false"` is only used in MySQL as it applies only to the DDL events emitted by the connector.

Reading the debezium docs, by default the `truncate` event is skipped, will add this to next release.
skipped.operations: "none"

**Comment by subkanthi** [comment]
Hi @Roman2dot0 , can u please share your full config, Im not able to get the truncate events.

**Comment by Roman2dot0** [comment]
```
#### Some of the properties are part of Debezium PostgreSQL Connector
#### https://debezium.io/documentation/reference/stable/connectors/postgresql.html
# name: Unique name for the connector. Attempting to register again with the same name will fail.
name: "altinity-lt-connector"

# database.hostname: IP address or hostname of the PostgreSQL database server.
database.hostname: "db.server.local"

# database.port: Integer port number of the PostgreSQL database server listening for client connections.
database.port: "5432"

# database.user: Name of the PostgreSQL database user to be used when connecting to the database.
database.user: "db_user"

# database.password: Password of the PostgreSQL database user to be used when connecting to the database.
database.password: "coolpasscode"

# database.server.name: The name of the PostgreSQL database from which events are to be captured when not using snapshot mode.
database.server.name: "db"

# schema.include.list: An optional list of regular expressions that match schema names to be monitored;
schema.include.list: public

# plugin.name:  The name of the PostgreSQL logical decoding plug-in installed on the PostgreSQL server. Supported values are decoderbufs, and pgoutput.
plugin.name: "pgoutput"

# table.include.list: An optional list of regular expressions that match fully-qualified table identifiers for tables to be monitored;
table.include.list: "public.table"

# clickhouse.server.url: Specify only the hostname of the Clickhouse Server.
clickhouse.server.url: "click-server"

# clickhouse.server.user: Clickhouse Server User
clickhouse.server.user: "altinity"

# clickhouse.server.password: Clickhouse Server Password
clickhouse.server.password: "altinitypasscode"

# clickhouse.server.port: Clickhouse Server Port
clickhouse.server.port: "8123"

# DEPRECATED since 2.1.0
# clickhouse.server.database: Clickhouse Server Database
clickhouse.server.database: "db"

# database.allowPublicKeyRetrieval: "true" https://rmoff.net/2019/10/23/debezium-mysql-v8-public-key-retrieval-is-not-allowed/
database.allowPublicKeyRetrieval: "true"

# snapshot.mode: Debezium can use different modes when it runs a snapshot. The snapshot mode is determined by the snapshot.mode configuration property.
snapshot.mode: "never"

# offset.flush.interval.ms: The number of milliseconds to wait before flushing recent offsets to Kafka. This ensures that offsets are committed within the specified time interval.
offset.flush.interval.ms: 5000

# connector.class: The Java class for the connector. This must be set to io.debezium.connector.postgresql.PostgresConnector.
connector.class: "io.debezium.connector.postgresql.PostgresConnector"

offset.storage: "io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore"
offset.storage.jdbc.offset.table.name: "altinity_sink_connector.replica_source_info"
offset.storage.jdbc.url: "jdbc:clickhouse://click-server:8123/altinity_sink_connector"
offset.storage.jdbc.user: "altinity"
offset.storage.jdbc.password: "altinitypasscode"
offset.storage.jdbc.offset.table.ddl: |-
  CREATE TABLE if not exists %s
  (
    `id` String,
    `offset_key` String,
    `offset_val` String,
    `record_insert_ts` DateTime,
    `record_insert_seq` UInt64,
    `_version` UInt64 MATERIALIZED toUnixTimestamp64Nano(now64(9))
  )
  ENGINE = ReplacingMergeTree(_version)
  ORDER BY id
  SETTINGS index_granularity = 8198
offset.storage.jdbc.offset.table.delete: "delete from %s where 1=1"

schema.history.internal: "io.debezium.storage.jdbc.history.JdbcSchemaHistory"
schema.history.internal.jdbc.url: "jdbc:clickhouse://click-server:8123/altinity_sink_connector"
schema.history.internal.jdbc.user: "altinity"
schema.history.internal.jdbc.password: "altinitypasscode"
schema.history.internal.jdbc.schema.history.table.ddl: |-
  CREATE TABLE if not exists %s
  (
    `id` VARCHAR(36) NOT NULL, 
    `history_data` VARCHAR(65000), 
    `history_data_seq` INTEGER, 
    `record_insert_ts` TIMESTAMP NOT NULL, 
    `record_insert_seq` INTEGER NOT NULL
  ) 
  ENGINE=ReplacingMergeTree(record_insert_seq) order by id
schema.history.internal.jdbc.schema.history.table.name: "altinity_sink_connector.replicate_schema_history"

# enable.snapshot.ddl: If set to true, the connector wil parse the DDL statements as part of initial load.
enable.snapshot.ddl: "true"

# auto.create.tables: If set to true, the connector will create the database tables for the destination tables if they do not already exist.
auto.create.tables: "true"

# database.dbname: The name of the PostgreSQL database from which events are to be captured when not using snapshot mode.
database.dbname: "db"

# clickhouse.datetime.timezone: This timezone will override the default timezone of ClickHouse server. Timezone columns will be set to this timezone.
#clickhouse.datetime.timezone: "UTC"

# skip_replica_start: If set to true, the connector will skip replication on startup. sink-connector-client start_replica will start replication.
skip_replica_start: "false"

# binary.handling.mode: The mode for handling binary values. Possible values are bytes, base64, and decode. The default is bytes.
binary.handling.mode: "bytes"

# ignore_delete: If set to true, the connector will ignore delete events. The default is false.
ignore_delete: "false"

#disable.ddl: If set to true, the connector will ignore DDL events. The default is false.
disable.ddl: "false"

#disable.drop.truncate: If set to true, the connector will ignore drop and truncate events. The default is false.
disable.drop.truncate: "false"


### CUSTOM ###
publication.autocreate.mode: "filtered"
publication.name: "publication"
skipped.operations: "none"
```
