### ISSUE TITLE
Update lsn (For postgreSQL) ????

### ISSUE THREAD

**Issue by byte09** [Altinity/clickhouse-sink-connector#748]
Hi, 
 can you help me with 'Update lsn (For postgreSQL)'  

Make a command:
  sink-connector-client lsn -- lsn 1/12ABC380

But have error:

2024-08-13 07:41:51.979 INFO  - Streaming requested from LSN LSN{1/FA42F50}, received LSN LSN{1/FA42F50} identified as already processed
2024-08-13 07:41:51.995 INFO  - Message with LSN 'LSN{1/FA43020}' arrived, switching off the filtering
2024-08-13 07:41:52.248 WARN  - Primary keys are not defined for table 'databasechangelog', defaulting to unique indices
2024-08-13 07:42:41.434 INFO  - 1 records sent during previous 00:00:49.837, last recorded offset of {server=embeddedconnector} partition is {lsn_proc=4605670336, messageType=UPDATE, lsn_commit=4603788280, lsn=4605670336, txId=698706, ts_usec=1723534961249010}
2024-08-13 07:42:41.452 INFO  - ****** Thread: Sink Connector thread-pool-8 Batch Size: 1 ******
2024-08-13 07:42:41.501 INFO  - getTableEngineUsingSystemTables ResultSetcom.clickhouse.jdbc.ClickHouseResultSet@5a64bf8e
2024-08-13 07:42:41.510 INFO  - *** INSERT QUERY for Database(metrika) ***: insert into `products`(`dateofrep`,`product_id`,`name`,`description`,`_version`) select `dateofrep`,`product_id`,`name`,`description`,`_version` from input('`dateofrep` Nullable(String),`product_id` Int64,`name` String,`description` String,`_version` UInt64')
2024-08-13 07:42:41.543 INFO  - *************** EXECUTED BATCH Successfully Records: 2************** task(0) Thread ID: Sink Connector thread-pool-8 Result: [I@57b75a89 Database: db_paperless Table: products
2024-08-13 07:42:41.581 INFO  - ***** BATCH marked as processed to debezium ****Binlog file: Binlog position: 0 GTID: -1 Sequence Number: 1723534962329000001 Debezium Timestamp: 1723534961329
2024-08-13 10:00:34.470 INFO  - 1 records sent during previous 02:17:53.036, last recorded offset of {server=embeddedconnector} partition is {lsn_proc=4608239368, messageType=UPDATE, lsn_commit=4608239312, lsn=4608239368, txId=698773, ts_usec=1723543234293447}
2024-08-13 10:00:34.475 INFO  - ****** Thread: Sink Connector thread-pool-3 Batch Size: 1 ******
2024-08-13 10:00:34.513 INFO  - getTableEngineUsingSystemTables ResultSetcom.clickhouse.jdbc.ClickHouseResultSet@6e15af1
2024-08-13 10:00:34.516 INFO  - *** INSERT QUERY for Database(metrika) ***: insert into `products`(`dateofrep`,`product_id`,`name`,`description`,`_version`) select `dateofrep`,`product_id`,`name`,`description`,`_version` from input('`dateofrep` Nullable(String),`product_id` Int64,`name` String,`description` String,`_version` UInt64')
2024-08-13 10:00:34.521 INFO  - *************** EXECUTED BATCH Successfully Records: 2************** task(0) Thread ID: Sink Connector thread-pool-3 Result: [I@7fd7be17 Database: db_paperless Table: products
2024-08-13 10:00:34.537 INFO  - ***** BATCH marked as processed to debezium ****Binlog file: Binlog position: 0 GTID: -1 Sequence Number: 1723543235400000002 Debezium Timestamp: 1723543234400
2024-08-13 10:00:38.481 INFO  - ****** Thread: Sink Connector thread-pool-5 Batch Size: 1 ******
2024-08-13 10:00:38.481 INFO  - *** INSERT QUERY for Database(metrika) ***: insert into `products`(`dateofrep`,`product_id`,`name`,`description`,`_version`) select `dateofrep`,`product_id`,`name`,`description`,`_version` from input('`dateofrep` Nullable(String),`product_id` Int64,`name` String,`description` String,`_version` UInt64')
2024-08-13 10:00:38.487 INFO  - *************** EXECUTED BATCH Successfully Records: 2************** task(0) Thread ID: Sink Connector thread-pool-5 Result: [I@64e50e2d Database: db_paperless Table: products
2024-08-13 10:00:38.506 INFO  - ***** BATCH marked as processed to debezium ****Binlog file: Binlog position: 0 GTID: -1 Sequence Number: 1723543239443000003 Debezium Timestamp: 1723543238443
2024-08-13 10:09:29.654 INFO  - Stopping the embedded engine
2024-08-13 10:09:29.654 INFO  - Waiting for PT5M for connector to stop
2024-08-13 10:09:30.045 INFO  - Stopping the task and engine
2024-08-13 10:09:30.045 INFO  - Stopping down connector
2024-08-13 10:09:30.382 INFO  - Connection gracefully closed
2024-08-13 10:09:30.382 INFO  - Connection gracefully closed
2024-08-13 10:09:30.383 INFO  - Finished streaming
2024-08-13 10:09:30.383 INFO  - Connected metrics set to 'false'
2024-08-13 10:09:30.384 INFO  - SignalProcessor stopped
2024-08-13 10:09:30.384 INFO  - Debezium ServiceRegistry stopped.
2024-08-13 10:09:30.385 INFO  - Connection gracefully closed
2024-08-13 10:09:30.386 INFO  - Stopped JdbcOffsetBackingStore
2024-08-13 10:20:45.910 INFO  - Stopping the embedded engine
**2024-08-13 10:20:50.949 WARN  - Uncaught exception
java.lang.NumberFormatException: For input string: "1/12ABC380"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
	at java.lang.Long.parseLong(Long.java:711) ~[?:?]
	at java.lang.Long.parseLong(Long.java:836) ~[?:?]
	at** com.altinity.clickhouse.debezium.embedded.cdc.DebeziumChangeEventCapture.updateDebeziumStorageStatus(DebeziumChangeEventCapture.java:545) ~[app.jar:?]
	at com.altinity.clickhouse.debezium.embedded.api.DebeziumEmbeddedRestApi.lambda$startRestApi$4(DebeziumEmbeddedRestApi.java:113) ~[app.jar:?]
	at io.javalin.routing.HandlerEntry.handle(HandlerEntry.kt:19) ~[app.jar:?]
	at io.javalin.http.servlet.DefaultTasks.HTTP$lambda$8$lambda$6$lambda$5(DefaultTasks.kt:38) ~[app.jar:?]

**Comment by byte09** [comment]
Hi, can you help me with error:

2024-08-13 10:20:50.949 WARN - Uncaught exception
java.lang.NumberFormatException: For input string: "1/12ABC380"
at java.lang.NumberFormatException.forInputString(NumberFormatException.java:67) ~[?:?]
at java.lang.Long.parseLong(Long.java:711) ~[?:?]
at java.lang.Long.parseLong(Long.java:836) ~[?:?]

?

**Comment by subkanthi** [comment]
Hi @byte09 
The current logic , the lsn needs to be converted from hex to number, the part after the slash.
0/**1A371A0**  to **27488672**

```sink-connector-client lsn -- lsn 27488672```

**Comment by subkanthi** [comment]
With the fix in #752, the `sink-connector-client` will support `lsn` values of both long values and Hex values.

**Comment by subkanthi** [comment]
closes: #752
