### ISSUE TITLE
Cannot set null to non-nullable column #7 [_sign UInt8]

### ISSUE THREAD

**Issue by byte09** [Altinity/clickhouse-sink-connector#758]
Hello, i also have exception:

2024-08-16 08:33:33.296 ERROR - ******* ERROR inserting Batch Database(db_paperless), Table(client_info) *****************
java.sql.SQLException: Cannot set null to non-nullable column #7 [_sign UInt8]
	at com.clickhouse.jdbc.SqlExceptionUtils.clientError(SqlExceptionUtils.java:73) ~[app.jar:?]
	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.addBatch(InputBasedPreparedStatement.java:341) ~[app.jar:?]
	
Problem with null column _sign. Why colum _sign is null ?

Can you help me?

**Comment by subkanthi** [comment]
Hi @byte09 , are you using version `2.2.1`, this exception is normally caused by mismatch in columns between source and ClickHouse.
