### ISSUE TITLE
Support for nullable JSON fields

### ISSUE THREAD

**Issue by aadant** [Altinity/clickhouse-sink-connector#79]
Example from world_x database 

2 issues 

- DB::Exception: Nested type Object('json') cannot be inside Nullable type. 
- JSON is currenlty experimental : set allow_experimental_object_type = 1 to create the table
```
Table from world_x :

 CREATE TABLE `countryinfo` (
  `doc` json DEFAULT NULL,
  `_id` varbinary(32) GENERATED ALWAYS AS (json_unquote(json_extract(`doc`,_utf8mb4'$._id'))) STORED NOT NULL,
  `_json_schema` json GENERATED ALWAYS AS (_utf8mb4'{"type":"object"}') VIRTUAL,
  PRIMARY KEY (`_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci


CREATE TABLE countryinfo(`doc` JSON NULL,`_id` String NOT NULL,`_json_schema` JSON NULL,`sign` Int8,`ver` UInt64) ENGINE = ReplacingMergeTree(ver) PRIMARY KEY(_id) ORDER BY(_id)
 
2022-09-11 22:18:54,460 ERROR  ||  **** Error creating table ***countryinfo   [com.altinity.clickhouse.sink.connector.db.DbWriter]
java.sql.SQLException: Code: 43. DB::Exception: Nested type Object('json') cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT) (version 22.8.4.7 (official build))
, server ClickHouseNode [uri=http://clickhouse:8123/world_x, options={client_name=Agent_1}]@1498614193
        at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85)
        at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31)
        at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90)
        at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:96)
        at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeQuery(ClickHouseStatementImpl.java:304)
        at com.altinity.clickhouse.sink.connector.db.operations.ClickHouseTableOperationsBase.runQuery(ClickHouseTableOperationsBase.java:85)
        at com.altinity.clickhouse.sink.connector.db.operations.ClickHouseAutoCreateTable.createNewTable(ClickHouseAutoCreateTable.java:26)
        at com.altinity.clickhouse.sink.connector.db.DbWriter.<init>(DbWriter.java:97)
        at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.getDbWriterForTable(ClickHouseBatchRunnable.java:143)
        at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:168)
        at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:105)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: Code: 43. DB::Exception: Nested type Object('json') cannot be inside Nullable type. (ILLEGAL_TYPE_OF_ARGUMENT) (version 22.8.4.7 (official build))

        at com.clickhouse.client.http.HttpUrlConnectionImpl.checkResponse(HttpUrlConnectionImpl.java:194)
        at com.clickhouse.client.http.HttpUrlConnectionImpl.post(HttpUrlConnectionImpl.java:289)
        at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:123)
        at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:296)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:284)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:296)
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:351)
        at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:824)
        at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:1972)
        at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.getLastResponse(ClickHouseStatementImpl.java:94)
        ... 13 more
		
Code: 44. DB::Exception: Received from localhost:9000. DB::Exception: Cannot create table with column 'doc' which type is 'Object('json')' because experimental Object type is not allowed. Set setting allow_experimental_object_type = 1 in order to allow it. (ILLEGAL_COLUMN)

```

**Comment by aadant** [comment]
Same thing with city : 
```
 CREATE TABLE `city` (
  `ID` int NOT NULL AUTO_INCREMENT,
  `Name` char(35) NOT NULL DEFAULT '',
  `CountryCode` char(3) NOT NULL DEFAULT '',
  `District` char(20) NOT NULL DEFAULT '',
  `Info` json DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=4080 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

**Comment by subkanthi** [comment]
Need to figure out a way to set allow_experimental_object_type in JDBC and remove NULL for JSON data types.

set allow_experimental_object_type = 1;
CREATE TABLE countryinfo(`doc` JSON,`_id` String NOT NULL,`_json_schema` JSON,`_sign` Int8,`_version` UInt64) ENGINE = ReplacingMergeTree(_version) PRIMARY KEY(_id) ORDER BY(_id);

**Comment by subkanthi** [comment]
There is a still outstanding bug in ClickHouse with writing JSON columns in batch insert - #27

**Comment by minguyen9988** [comment]
Verified at develop head `e123450c8`. Both reported failures are resolved, and the two items named in the maintainer comment above are implemented.

1. Setting allow_experimental_object_type in JDBC — `sink-connector/src/main/java/com/altinity/clickhouse/sink/connector/db/BaseDbWriter.java:350` now sets the custom_settings property to `allow_experimental_object_type=1,insert_allow_materialized_columns=1` on every connection.

2. Removing NULL for JSON data types — `sink-connector/src/main/java/com/altinity/clickhouse/sink/connector/db/operations/ClickHouseAutoCreateTable.java:145-149`:
```
// Ignore setting NULL/NOT NULL for JSON and Array types.
if (dataType != null
        && (dataType.equalsIgnoreCase(ClickHouseDataType.JSON.name())
        || dataType.contains(ClickHouseDataType.Array.name()))) {
```
so the ILLEGAL_TYPE_OF_ARGUMENT DDL reported here can no longer be generated.

Source JSON also no longer maps to the experimental object type: `converters/ClickHouseDataTypeMapper.java:191-194` maps Json.LOGICAL_NAME to ClickHouseDataType.String. Covered by `sink-connector-lightweight/src/test/java/com/altinity/clickhouse/debezium/embedded/MySQLJsonIT.java:100`. Nuance: the nullable-JSON errors are resolved by storing JSON as String rather than as a native ClickHouse JSON column; native JSON typing is tracked separately in #27. Please reopen if the native-column behaviour was the intent here.
