### ISSUE TITLE
Lightweight sink connector faces some error after initial load and then truncates all tables

### ISSUE THREAD

**Issue by cb-shreyassreenivas** [Altinity/clickhouse-sink-connector#790]
I'm trying sync data from RDS Mysql. I used the sink-connector-lightweight. 
It created the tables and started syncing all the data. But once it was done it threw the following error
```
clickhouse-sink-connector-lt-1  | 2024-09-04 17:34:47.833 ERROR - Error during binlog processing. Last offset stored = null, binlog reader near position = /4
clickhouse-sink-connector-lt-1  | 2024-09-04 17:34:47.850 ERROR - Producer failure
clickhouse-sink-connector-lt-1  | 2024-09-04 17:34:48.055 ERROR - Error parsing precision, scale : columnName`state`
clickhouse-sink-connector-lt-1  | 2024-09-04 17:34:51.088 ERROR - Error parsing precision, scale : columnName`support_email`
```

I'm not sure what the issue is. Am I doing something wrong to see this error?

**Comment by subkanthi** [comment]
This could be related to the binlogs purged in RDS, can you check the binlog retention https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/mysql-stored-proc-configuring.html

**Comment by cb-shreyassreenivas** [comment]
This was the issue. thanks!!

**Comment by Jimerson21** [comment]
Hello everyone,

I have the same problem, I would like to know if there is a way to recover the binglog so that the sink connector can complete the process. I am using Aurora Serverless Mysql.

```
clickhouse-sink-connector-lt-1  | 2024-09-26 08:25:50.241 INFO  - Snapshot - Final stage
clickhouse-sink-connector-lt-1  | 2024-09-26 08:25:50.241 INFO  - Snapshot completed
clickhouse-sink-connector-lt-1  | 2024-09-26 08:25:50.241 INFO  - Snapshot ended with SnapshotResult [status=COMPLETED, offset=BinlogOffsetContext{sourceInfoSchema=Schema{io.debezium.connector.mysql.Source:STRUCT}, sourceInfo=BinlogSourceInfo{currentGtid='null', currentBinlogFilename='mysql-bin-changelog.000053', currentBinlogPosition=90509983, currentRowNumber=0, serverId=0, sourceTime=2024-09-26T08:25:47Z, threadId=-1, currentQuery='null', tableIds=[], databaseName=''}, snapshotCompleted=true, transactionContext=TransactionContext [currentTransactionId=null, perTableEventCount={}, totalEventCount=0], restartGtidSet='e5eafe0e-1211-3aa5-b34b-3c9583e98979:1-2184075', currentGtidSet='e5eafe0e-1211-3aa5-b34b-3c9583e98979:1-2184075', restartBinlogFilename='mysql-bin-changelog.000053', restartBinlogPosition=90509983, restartRowsToSkip=0, restartEventsToSkip=0, currentEventLengthInBytes=0, inTransaction=false, transactionId='null', incrementalSnapshotContext=IncrementalSnapshotContext [windowOpened=false, chunkEndPosition=null, dataCollectionsToSnapshot=[], lastEventKeySent=null, maximumKey=null]}]

clickhouse-sink-connector-lt-1  | 2024-09-26 08:25:50.525 INFO  - Connected to binlog at , starting at BinlogOffsetContext{sourceInfoSchema=Schema{io.debezium.connector.mysql.Source:STRUCT}, sourceInfo=BinlogSourceInfo{currentGtid='null', currentBinlogFilename='mysql-bin-changelog.000053', currentBinlogPosition=90509983, currentRowNumber=0, serverId=0, sourceTime=2024-09-26T08:25:47Z, threadId=-1, currentQuery='null', tableIds=[], databaseName=''}, snapshotCompleted=true, transactionContext=TransactionContext [currentTransactionId=null, perTableEventCount={}, totalEventCount=0], restartGtidSet='e5eafe0e-1211-3aa5-b34b-3c9583e98979:1-2184075', currentGtidSet='e5eafe0e-1211-3aa5-b34b-3c9583e98979:1-2184075', restartBinlogFilename='mysql-bin-changelog.000053', restartBinlogPosition=90509983, restartRowsToSkip=0, restartEventsToSkip=0, currentEventLengthInBytes=0, inTransaction=false, transactionId='null', incrementalSnapshotContext=IncrementalSnapshotContext [windowOpened=false, chunkEndPosition=null, dataCollectionsToSnapshot=[], lastEventKeySent=null, maximumKey=null]}
clickhouse-sink-connector-lt-1  | 2024-09-26 08:25:50.526 INFO  - Waiting for keepalive thread to start
clickhouse-sink-connector-lt-1  | 2024-09-26 08:25:50.526 INFO  - Creating thread debezium-mysqlconnector-embeddedconnector-binlog-client
clickhouse-sink-connector-lt-1  | 2024-09-26 08:25:50.532 ERROR - Error during binlog processing. Last offset stored = null, binlog reader near position = /4
clickhouse-sink-connector-lt-1  | Sep 26, 2024 8:25:50 AM com.github.shyiko.mysql.binlog.BinaryLogClient$5 run
clickhouse-sink-connector-lt-1  | INFO: threadExecutor is shut down, terminating keepalive thread
clickhouse-sink-connector-lt-1  | 2024-09-26 08:25:50.533 INFO  - threadExecutor is shut down, terminating keepalive thread
clickhouse-sink-connector-lt-1  | 2024-09-26 08:25:50.534 ERROR - Producer failure
clickhouse-sink-connector-lt-1  | io.debezium.DebeziumException: Cannot replicate because the source purged required binary logs. Replicate the missing transactions from elsewhere, or provision a new replica from backup. Consider increasing the source's binary log expiration period. The GTID set sent by the replica is 'e5eafe0e-1211-3aa5-b34b-3c9583e98979:1-2184075', and the missing transactions are 'e5eafe0e-1211-3aa5-b34b-3c9583e98979:2184076-2789502' Error code: 1236; SQLSTATE: HY000.
clickhouse-sink-connector-lt-1  |       at io.debezium.connector.binlog.BinlogStreamingChangeEventSource.wrap(BinlogStreamingChangeEventSource.java:1190) ~[app.jar:?]
clickhouse-sink-connector-lt-1  |       at io.debezium.connector.binlog.BinlogStreamingChangeEventSource$ReaderThreadLifecycleListener.onCommunicationFailure(BinlogStreamingChangeEventSource.java:1235) [app.jar:?]
clickhouse-sink-connector-lt-1  |       at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1101) [app.jar:?]
clickhouse-sink-connector-lt-1  |       at com.github.shyiko.mysql.binlog.BinaryLogClient.connect(BinaryLogClient.java:653) [app.jar:?]
clickhouse-sink-connector-lt-1  |       at com.github.shyiko.mysql.binlog.BinaryLogClient$7.run(BinaryLogClient.java:954) [app.jar:?]
clickhouse-sink-connector-lt-1  |       at java.lang.Thread.run(Thread.java:833) [?:?]
clickhouse-sink-connector-lt-1  | Caused by: com.github.shyiko.mysql.binlog.network.ServerException: Cannot replicate because the source purged required binary logs. Replicate the missing transactions from elsewhere, or provision a new replica from backup. Consider increasing the source's binary log expiration period. The GTID set sent by the replica is 'e5eafe0e-1211-3aa5-b34b-3c9583e98979:1-2184075', and the missing transactions are 'e5eafe0e-1211-3aa5-b34b-3c9583e98979:2184076-2789502'
clickhouse-sink-connector-lt-1  |       at com.github.shyiko.mysql.binlog.BinaryLogClient.listenForEventPackets(BinaryLogClient.java:1065) ~[app.jar:?]
```
Thanks!
