### ISSUE TITLE
'Saving offset': doing rollback.

### ISSUE THREAD

**Issue by tellienne** [Altinity/clickhouse-sink-connector#826]
Hi!
In v2.3.0-lt we see an error when running a snapshot

```
2024-09-18 18:10:08.037	
2024-09-18 11:10:08.037 WARN  - 'Saving offset': doing rollback.


2024-09-18 18:10:08.037	
	... 12 more
2024-09-18 18:10:08.037	
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getTableColumns(ClickHouseConnectionImpl.java:264) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:878) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:118) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.http.ApacheHttpConnectionImpl.post(ApacheHttpConnectionImpl.java:241) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:123) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:188) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:116) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:216) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:712) ~[app.jar:?]
2024-09-18 18:10:08.037	
	at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218) ~[app.jar:?]
2024-09-18 18:10:08.036	
	at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175) ~[app.jar:?]
2024-09-18 18:10:08.036	
	at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:301) ~[app.jar:?]
2024-09-18 18:10:08.036	
Caused by: com.clickhouse.client.internal.apache.hc.core5.http.NoHttpResponseException: The target server failed to respond
2024-09-18 18:10:08.036	
	at java.lang.Thread.run(Thread.java:833) [?:?]
2024-09-18 18:10:08.036	
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
2024-09-18 18:10:08.036	
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
2024-09-18 18:10:08.036	
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
2024-09-18 18:10:08.036	
	at io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore$1.call(JdbcOffsetBackingStore.java:196) [app.jar:?]
2024-09-18 18:10:08.036	
	at io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore$1.call(JdbcOffsetBackingStore.java:205) [app.jar:?]
2024-09-18 18:10:08.036	
	at io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore.save(JdbcOffsetBackingStore.java:114) [app.jar:?]
2024-09-18 18:10:08.036	
	at io.debezium.storage.jdbc.RetriableConnection.executeWithRetry(RetriableConnection.java:98) [app.jar:?]
2024-09-18 18:10:08.036	
	at io.debezium.storage.jdbc.RetriableConnection.executeWithRetry(RetriableConnection.java:140) [app.jar:?]
2024-09-18 18:10:08.036	
	at io.debezium.storage.jdbc.offset.JdbcOffsetBackingStore.lambda$save$1(JdbcOffsetBackingStore.java:122) ~[app.jar:?]
2024-09-18 18:10:08.036	
	at com.clickhouse.jdbc.ClickHouseConnection.prepareStatement(ClickHouseConnection.java:121) ~[app.jar:?]
2024-09-18 18:10:08.036	
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.prepareStatement(ClickHouseConnectionImpl.java:843) ~[app.jar:?]
2024-09-18 18:10:08.036	
	at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getTableColumns(ClickHouseConnectionImpl.java:267) ~[app.jar:?]
2024-09-18 18:10:08.036	
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:90) ~[app.jar:?]
2024-09-18 18:10:08.036	
	at com.clickhouse.jdbc.SqlExceptionUtils.create(SqlExceptionUtils.java:31) ~[app.jar:?]
2024-09-18 18:10:08.036	
	at com.clickhouse.jdbc.SqlExceptionUtils.handle(SqlExceptionUtils.java:85) ~[app.jar:?]
2024-09-18 18:10:08.036	
java.sql.SQLException: The target server failed to respond, server ClickHouseNode [uri=http://172.18.160.7:8123/altinity_sink_connector]@-761901792
2024-09-18 18:10:08.036	
2024-09-18 11:10:08.036 WARN  - Attempt 1 to call 'Saving offset' failed.
```
clickhouse works, the connector writes rows to the table, but the snapshot does not end

**Comment by subkanthi** [comment]
It could be related to timeouts 
https://github.com/ClickHouse/clickhouse-java/issues/1444

**Comment by tellienne** [comment]
it looks like the problems started when we changed the entrypoint.
we tried to enable the collection of metrics from https://github.com/Altinity/clickhouse-sink-connector/issues/744. 
we see in the pull request https://github.com/Altinity/clickhouse-sink-connector/pull/757/commits/11d9ab5af6d1693972da5b47dc9a3a12b1c36add that the entrypoint had changed like 

```
["sh", "-c", "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms4g -Xmx4g -Dlog4j2.configurationFile=log4j2.xml -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=39999 -jar /app.jar /config.yml com.altinity.clickhouse.debezium.embedded.ClickHouseDebeziumEmbeddedApplication"]
```
we deploy connector in k8s. 
We updated the version to 2.3.0, but the collection of metrics did not work. After that we added to the deployment in container spec:
```
      containers:
          ports:
            - name: http
              containerPort: 8083
              protocol: TCP
            - name: jmxmetrics
              containerPort: 39999
              protocol: TCP              
          command: ["sh", "-c", "java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005 -Xms4g -Xmx4g -Dlog4j2.configurationFile=log4j2.xml -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=39999 -jar /app.jar /config.yml com.altinity.clickhouse.debezium.embedded.ClickHouseDebeziumEmbeddedApplication"]
```
after that, port 39999 became available in the container, and metrics collection started working. But errors about offset began. 
Now we have removed the command param from deployment and the errors have disappeared. 
or maybe they stopped being logged?

**Comment by tellienne** [comment]
The problem has already recurred several times during the day.
The connector seems to stop transmitting data, we do a restart and the connector starts snapshotting as if this is its first start. And then errors about offset begin. Increasing the keep_alive_timeout doesn't help. 
any ideas are welcome :(

**Comment by tellienne** [comment]
Hello!
It looks like this is really something on the clickhouse side, because yesterday it was reproduced in all our connectors with a difference of a couple of seconds. 
Does the connector reconnect after a message about  `'Saving offset': doing rollback.` and save offset on a new attempt?

**Comment by subkanthi** [comment]
> Hello! It looks like this is really something on the clickhouse side, because yesterday it was reproduced in all our connectors with a difference of a couple of seconds. Does the connector reconnect after a message about `'Saving offset': doing rollback.` and save offset on a new attempt?

Yes this is part of Debezium logic to retry the connection
```
    private synchronized <T> T executeWithRetry(ConnectionFunction<T> func, ConnectionConsumer consumer, String name, boolean rollback)
            throws SQLException {
        int attempt = 1;
        while (true) {
            if (!isOpen()) {
                LOGGER.debug("Trying to reconnect (attempt {}).", attempt);
                try {
                    createConnection();
                }
                catch (SQLException e) {
                    LOGGER.error("SQL Exception while trying to reconnect: {}", e.getMessage(), e);
                    close();
                    if (attempt >= maxRetryCount) {
                        throw e;
                    }
                    attempt++;
                    LOGGER.debug("Waiting for reconnect for {} ms.", waitRetryDelay);
                    DelayStrategy delayStrategy = DelayStrategy.constant(waitRetryDelay);
                    delayStrategy.sleepWhen(true);
                    continue;
                }
            }
            try {
                if (func != null) {
                    return func.accept(conn);
                }
                if (consumer != null) {
                    consumer.accept(conn);
                    return null;
                }
            }
            catch (SQLException e) {
                LOGGER.warn("Attempt {} to call '{}' failed.", attempt, name, e);
                if (rollback) {
                    LOGGER.warn("'{}': doing rollback.", name);
                    try {
                        conn.rollback();
                    }
                    catch (SQLException ex) {
                        // ignore
                    }
                }
                close();
            }
        }
    }```

**Comment by tellienne** [comment]
Thank you!
I think we can close the issue. We will observe the work of connectors and clickhouse.
