### ISSUE TITLE
REST API broken - sink-connector-client

### ISSUE THREAD

**Issue by subkanthi** [Altinity/clickhouse-sink-connector#843]
As a result of enabling serviceloader, javalin fails to start the REST API because of the following error

https://stackoverflow.com/questions/73123077/javalin-with-jpms-and-serviceloader-results-in-noclassdeffounderror-kotlin-nowh

```
Exception in thread "main" java.lang.NoClassDefFoundError: kotlin/NoWhenBranchMatchedException
	at io.javalin.config.PrivateConfig.<init>(PrivateConfig.kt:27)
	at io.javalin.config.JavalinConfig.<init>(JavalinConfig.kt:26)
	at io.javalin.Javalin.<init>(Javalin.java:55)
	at io.javalin.Javalin.create(Javalin.java:92)
	at io.javalin.Javalin.create(Javalin.java:79)
	at com.altinity.clickhouse.debezium.embedded.api.DebeziumEmbeddedRestApi.startRestApi(DebeziumEmbeddedRestApi.java:35)
	at com.altinity.clickhouse.debezium.embedded.ClickHouseDebeziumEmbeddedApplication.main(ClickHouseDebeziumEmbeddedApplication.java:93)
Caused by: java.lang.ClassNotFoundException: kotlin.NoWhenBranchMatchedException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 7 more

```

**Comment by subkanthi** [comment]
Fixed in #833
