### ISSUE TITLE
Potential Connection Leak in `createConnection` Method

### ISSUE THREAD

**Issue by MrDingz** [Altinity/clickhouse-sink-connector#867]
### Description
In the `createConnection` method, a new connection to ClickHouse is created each time the method is called. However, there is no code to close the connection after it is used. This can lead to a connection leak, especially in long-running applications where this method is frequently invoked.

#### Relevant Code:
The problematic code is as follows:

```java
/**
 * Function to create Connection using the JDBC Driver
 *
 * @param url        url with the JDBC format jdbc:ch://localhost/test
 * @param clientName Client Name
 * @param userName   UserName
 * @param password   Password
 */
public static ClickHouseConnection createConnection(String url, String clientName, String userName, String password,
        ClickHouseSinkConnectorConfig config) {

    String jdbcParams = "";
    ClickHouseConnection conn = null;
    if (config != null) {
        config.getString(ClickHouseSinkConnectorConfigVariables.JDBC_PARAMETERS.toString());
    }

    try {
        Properties properties = new Properties();
        properties.setProperty("client_name", clientName);
        properties.setProperty("custom_settings",
                "allow_experimental_object_type=1,insert_allow_materialized_columns=1");

        if (!jdbcParams.isEmpty()) {
            log.info("**** JDBC PARAMS from configuration:" + jdbcParams);
            Properties userProps = splitJdbcProperties(jdbcParams);
            properties.putAll(userProps);
        }
        ClickHouseDataSource dataSource = new ClickHouseDataSource(url, properties);
        conn = dataSource.getConnection(userName, password);
    } catch (Exception e) {
        log.error("Error creating ClickHouse connection：" + e);
    }

    return conn;
}
```

### Potential Issues
- **Connection Leak**: As connections are opened but never closed, this can result in a connection leak, causing system resource exhaustion over time.
- **Performance Impact**: Open but unused connections can consume memory and potentially affect the performance of the application.
- **Database Resource Utilization**: Leaving connections open can consume unnecessary resources on the ClickHouse server, impacting other processes or connections.

### Suggested Solution
1. **Ensure Connections are Closed**: Use a `try-with-resources` statement to automatically close the connection after use, as shown below:

    ```java
    try (ClickHouseConnection conn = dataSource.getConnection(userName, password)) {
        // Use the connection
    } catch (Exception e) {
        log.error("Error creating ClickHouse connection：" + e);
    }
    ```

2. **Consider Using a Connection Pool**: For better connection management and to avoid repeatedly creating and closing connections, it is recommended to use a connection pool, such as HikariCP. Here’s a simple example configuration:

    ```java
    HikariDataSource dataSource = new HikariDataSource();
    dataSource.setJdbcUrl(url);
    dataSource.setUsername(userName);
    dataSource.setPassword(password);
    // Additional configuration options
    ```

### Environment
- ClickHouse Sink Connector Version: [2.3]

### Steps to Reproduce
1. Continuously call the `createConnection` method in a loop without closing the connection.
2. Observe the system resources and connection count on the ClickHouse server.

### Expected Behavior
Connections should be properly closed after use to avoid leaks and optimize resource utilization.

### Actual Behavior
Connections are not closed, leading to a potential connection leak.

By implementing these changes, the connection handling in the application will be more efficient, and the risk of resource leaks will be minimized.

**Comment by subkanthi** [comment]
https://github.com/brettwooldridge/HikariCP

```

    static void usedPooledConnection(String url) throws SQLException {
        // connection pooling won't help much in terms of performance,
        // because the underlying implementation has its own pool.
        // for example: HttpURLConnection has a pool for sockets
        HikariConfig poolConfig = new HikariConfig();
        poolConfig.setConnectionTimeout(5000L);
        poolConfig.setMaximumPoolSize(20);
        poolConfig.setMaxLifetime(300_000L);
        poolConfig.setDataSource(new ClickHouseDataSource(url));

        HikariDataSource ds = new HikariDataSource(poolConfig);

        try (Connection conn = ds.getConnection();
                Statement s = conn.createStatement();
                ResultSet rs = s.executeQuery("select 123")) {
            System.out.println(rs.next());
            System.out.println(rs.getInt(1));
        }
    }

```

**Comment by subkanthi** [comment]
This error could be because of max connections used. 
```
btc-sink-dr___debezium-embedded | java.sql.BatchUpdateException: Broken pipe, server ClickHouseNode [ e, options={custom_settings=allow_experimental_object_type=1,insert_allow_materialized_columns=1,client_name=Sink Connector Lightweight}]@-551199967
btc-sink-dr___debezium-embedded | 	at com.clickhouse.jdbc.SqlExceptionUtils.batchUpdateError(SqlExceptionUtils.java:107) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeAny(InputBasedPreparedStatement.java:154) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.clickhouse.jdbc.internal.AbstractPreparedStatement.executeLargeBatch(AbstractPreparedStatement.java:85) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:752) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.db.batch.PreparedStatementExecutor.lambda$executePreparedStatement$0(PreparedStatementExecutor.java:160) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at java.lang.Iterable.forEach(Iterable.java:75) [?:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.db.batch.PreparedStatementExecutor.executePreparedStatement(PreparedStatementExecutor.java:117) [app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.db.batch.PreparedStatementExecutor.addToPreparedStatementBatch(PreparedStatementExecutor.java:86) [app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.flushRecordsToClickHouse(ClickHouseBatchRunnable.java:376) [app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:338) [app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:189) [app.jar:?]
btc-sink-dr___debezium-embedded | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
btc-sink-dr___debezium-embedded | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
btc-sink-dr___debezium-embedded | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
btc-sink-dr___debezium-embedded | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
btc-sink-dr___debezium-embedded | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
btc-sink-dr___debezium-embedded | 	at java.lang.Thread.run(Thread.java:833) [?:?]
btc-sink-dr___debezium-embedded | 2024-10-30 12:24:14.011 ERROR - ClickHouseBatchRunnable exception - Task(0)
btc-sink-dr___debezium-embedded | java.lang.RuntimeException: java.sql.BatchUpdateException: Broken pipe, server  , options={custom_settings=allow_experimental_object_type=1,insert_allow_materialized_columns=1,client_name=Sink Connector Lightweight}]@-551199967
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.db.batch.PreparedStatementExecutor.lambda$executePreparedStatement$0(PreparedStatementExecutor.java:176) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.db.batch.PreparedStatementExecutor.executePreparedStatement(PreparedStatementExecutor.java:117) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.db.batch.PreparedStatementExecutor.addToPreparedStatementBatch(PreparedStatementExecutor.java:86) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.flushRecordsToClickHouse(ClickHouseBatchRunnable.java:376) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.processRecordsByTopic(ClickHouseBatchRunnable.java:338) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.executor.ClickHouseBatchRunnable.run(ClickHouseBatchRunnable.java:189) [app.jar:?]
btc-sink-dr___debezium-embedded | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
btc-sink-dr___debezium-embedded | 	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [?:?]
btc-sink-dr___debezium-embedded | 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) [?:?]
btc-sink-dr___debezium-embedded | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
btc-sink-dr___debezium-embedded | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
btc-sink-dr___debezium-embedded | 	at java.lang.Thread.run(Thread.java:833) [?:?]
btc-sink-dr___debezium-embedded | Caused by: java.sql.BatchUpdateException: Broken pipe, server ClickHouseNode  , options={custom_settings=allow_experimental_object_type=1,insert_allow_materialized_columns=1,client_name=Sink Connector Lightweight}]@-551199967
btc-sink-dr___debezium-embedded | 	at com.clickhouse.jdbc.SqlExceptionUtils.batchUpdateError(SqlExceptionUtils.java:107) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.clickhouse.jdbc.internal.InputBasedPreparedStatement.executeAny(InputBasedPreparedStatement.java:154) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.clickhouse.jdbc.internal.AbstractPreparedStatement.executeLargeBatch(AbstractPreparedStatement.java:85) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.clickhouse.jdbc.internal.ClickHouseStatementImpl.executeBatch(ClickHouseStatementImpl.java:752) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	at com.altinity.clickhouse.sink.connector.db.batch.PreparedStatementExecutor.lambda$executePreparedStatement$0(PreparedStatementExecutor.java:160) ~[app.jar:?]
btc-sink-dr___debezium-embedded | 	... 12 more
btc-sink-dr___debezium-embedded | 2024-10-30 12:42:30.014 ERROR - Error creating ClickHouse connectionjava.sql.SQLException: Connect to   timed out, server ClickHouseNode [ur  options={custom_settings=allow_experimental_object_type=1,insert_allow_materialized_columns=1,client_name=Sink Connector Lightweight}]@-669042
```

**Comment by subkanthi** [comment]
Query to check the number of connections
```
select user, address, count(*) from system.processes group by user, address;

SELECT
    user,
    address,
    count(*)
FROM system.processes
GROUP BY
    user,
    address
```

**Comment by subkanthi** [comment]
There is a limit of 10 connections set in clickhouse-jdbc for the Apache Http Connection pool

https://github.com/ClickHouse/clickhouse-java/issues/1705
https://github.com/ClickHouse/clickhouse-java/issues/1817

**Comment by subkanthi** [comment]
when that limit is reached all the newer connections are blocked
```
2025-02-19 16:28:45.008 DEBUG - ep-0000004469 connection released [route: {}->http://clickhouse:8123][total available: 0; route allocated: 0 of 10; total allocated: 0 of 10]
2025-02-19 16:28:45.008 DEBUG - ep-0000004470 connection released [route: {}->http://clickhouse:8123][total available: 0; route allocated: 0 of 10; total allocated: 0 of 10]
2025-02-19 16:28:45.008 DEBUG - http-outgoing-4104 Close connection
2025-02-19 16:28:45.008 DEBUG - http-outgoing-4104 >> "0[\r][\n]"
2025-02-19 16:28:45.008 DEBUG - ex-0000004470 cannot retry non-repeatable request
2025-02-19 16:28:45.008 DEBUG - http-outgoing-4104 >> "[\r][\n]"
2025-02-19 16:28:45.008 DEBUG - ex-0000004469 cannot retry non-repeatable request
2025-02-19 16:28:45.008 DEBUG - http-outgoing-4104 >> "[write] I/O error: Broken pipe"
2025-02-19 16:28:45.008 ERROR - HTTP request failed
java.net.SocketException: Broken pipe
        at sun.nio.ch.NioSocketImpl.implWrite(NioSocketImpl.java:420) ~[?:?]
        at sun.nio.ch.NioSocketImpl.write(NioSocketImpl.java:440) ~[?:?]
        at sun.nio.ch.NioSocketImpl$2.write(NioSocketImpl.java:826) ~[?:?]
        at java.net.Socket$SocketOutputStream.write(Socket.java:1035) ~[?:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.io.LoggingOutputStream.write(LoggingOutputStream.java:72) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection$1.write(DefaultBHttpClientConnection.java:232) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flushBuffer(SessionOutputBufferImpl.java:117) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.SessionOutputBufferImpl.flush(SessionOutputBufferImpl.java:126) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.ChunkedOutputStream.close(ChunkedOutputStream.java:246) ~[app.jar:?]
        at com.clickhouse.data.stream.WrappedOutputStream.close(WrappedOutputStream.java:45) ~[app.jar:?]
        at com.clickhouse.client.http.ClickHouseHttpConnection.postData(ClickHouseHttpConnection.java:367) ~[app.jar:?]
        at com.clickhouse.client.http.ClickHouseHttpEntity.writeTo(ClickHouseHttpEntity.java:57) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.RequestEntityProxy.writeTo(RequestEntityProxy.java:106) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.sendRequestEntity(DefaultBHttpClientConnection.java:253) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:141) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:712) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:216) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:116) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:188) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:192) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:96) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:115) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:170) ~[app.jar:?]
        at com.clickhouse.client.internal.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:123) ~[app.jar:?]
        at com.clickhouse.client.http.ApacheHttpConnectionImpl.post(ApacheHttpConnectionImpl.java:280) [app.jar:?]
        at com.clickhouse.client.http.ClickHouseHttpClient.send(ClickHouseHttpClient.java:195) [app.jar:?]
        at com.clickhouse.client.AbstractClient.execute(AbstractClient.java:280) [app.jar:?]
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.sendOnce(ClickHouseClientBuilder.java:282) [app.jar:?]
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.send(ClickHouseClientBuilder.java:294) [app.jar:?]
        at com.clickhouse.client.ClickHouseClientBuilder$Agent.execute(ClickHouseClientBuilder.java:349) [app.jar:?]
        at com.clickhouse.client.ClickHouseClient.executeAndWait(ClickHouseClient.java:878) [app.jar:?]
        at com.clickhouse.client.ClickHouseRequest.executeAndWait(ClickHouseRequest.java:2154) [app.jar:?]
        at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.getServerInfo(ClickHouseConnectionImpl.java:128) [app.jar:?]
        at com.clickhouse.jdbc.internal.ClickHouseConnectionImpl.<init>(ClickHouseConnectionImpl.java:335) [app.jar:?]
        at com.clickhouse.jdbc.ClickHouseDataSource.getConnection(ClickHouseDataSource.java:46) [app.jar:?]
        at com.clickhouse.jdbc.ClickHouseDataSource.getConnection(ClickHouseDataSource.java:16) [app.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:362) [app.jar:?]
        at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:203) [app.jar:?]
        at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:479) [app.jar:?]
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:744) [app.jar:?]
        at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:723) [app.jar:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
2025-02-19 16:28:45.009 DEBUG - ep-0000004471 endpoint closed

```

**Comment by subkanthi** [comment]
https://github.com/ClickHouse/clickhouse-java/issues/1713, good summary of enabling Application connection pool and disabling the java client connection pool.
