### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by giriputraa** [Altinity/clickhouse-sink-connector#888]
```
2024-10-29 03:45:55.863 ERROR - Producer failure
io.debezium.DebeziumException: java.util.concurrent.ExecutionException: java.lang.OutOfMemoryError: Java heap space
	at io.debezium.pipeline.source.AbstractSnapshotChangeEventSource.execute(AbstractSnapshotChangeEventSource.java:105) ~[app.jar:?]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:285) ~[app.jar:?]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.doSnapshot(ChangeEventSourceCoordinator.java:269) ~[app.jar:?]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.executeChangeEventSources(ChangeEventSourceCoordinator.java:192) ~[app.jar:?]
	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:143) ~[app.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) [?:?]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

I keep getting this issue when running docker-compose-mysql-standalone. I tried increasing the max heap size to 8gb, -Xms4g -Xmx8g, but it still hit this error. Barely any of the data has been successfully moved. I'm really not sure if it is a configuration issue or something else. For config.yml I used most of the default settings.

**Comment by subkanthi** [comment]
Hi @giriputraa , does it help if u add the `single.threaded: true` to config.yml .

https://github.com/Altinity/clickhouse-sink-connector/blob/develop/doc/production_setup.md
